### ISSUE TITLE
Does not accept custom recipe for compounds with space character in name

### ISSUE THREAD

**Issue by finalsabbath** [al132mc/alchemistry#10]
May be a way but I have not found one yet.  

Recipe:

![image](https://user-images.githubusercontent.com/40742722/42384090-1028c0f8-8107-11e8-8361-3ee10fe8c3ff.png)

Result

![image](https://user-images.githubusercontent.com/40742722/42383889-9df4cb62-8106-11e8-9d88-b571d5153751.png)

Versions
MC 1.12.2
Forge 14.23.4.2729
Alchemistry 0.7.11

**Comment by al132mc** [comment]
Compounds with multiple words do work if you use an underscore, i.e. silicon_dioxide, though I think I will allow spaces as well in the next version, so i'll leave this issue open as a reminder

**Comment by finalsabbath** [comment]
Thanks again.  Worked with no issues
![image](https://user-images.githubusercontent.com/40742722/42396477-d50d583e-812f-11e8-91aa-35f59c4209ea.png)

**Comment by al132mc** [comment]
v0.7.12 is now up which allows either spaces or underscores
