### ISSUE TITLE
[Suggestion] Add elemental symbol in brackets to item name

### ISSUE THREAD

**Issue by Gepett0** [al132mc/alchemistry#101]
Dear mod creator :-)

Could you kindly add the elemental symbols to the item names?
e.g. Lead (Pb)

I'm playing Minecraft in English usually, but English is not my native language.
So sometimes while playing I get confused looking for elements inside the PE transmutaion table
(yeah, playing Chemical Exchange atm).
I know most of the elements in my native tongue, but some elements differ in English from their corresponding symbol. eg is K(alium) Potassium in English.
Other examples for elements I get confused with: Iron - Always looking for Fe(rrum), Lead - P(lum)b(um), Copper - Cu(prum), Tungsten - W(olfram)

Would be a huge QoL if you could add my suggestion.

Sincerly
Gepetto

**Comment by Dark-Arcana** [comment]
Closing this issue as it's related to ChemLib. Opening a new issue for ChemLib and will add this feature soon.
