### ISSUE TITLE
{Reminder} Alchemistry Mod, V.1.14.4! 

### ISSUE THREAD

**Issue by KingDarkIce** [al132mc/alchemistry#102]
Al, this is just a reminder to add a recipe for Bamboo into the Mod as 1.14.4 has Bamboo but no recipe in the machine as does Sugar Cane, Wheat, Beetroot, Melon, Pumpkin, Potatoes and Carrots do.

**Comment by ghost** [comment]
I'm no longer supporting 1.14.4, but this has added in 1.16.4-4, thank you
