### ISSUE TITLE
{Reminder} CraftTweaker Support for 1.14.4

### ISSUE THREAD

**Issue by Nachtflame** [al132mc/alchemistry#106]
Looking forward to being able to customize recipes via CraftTweaker, just wanted to make sure it wasn't forgotten. :)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
