### ISSUE TITLE
[suggestion,simplification]command window in game converter

### ISSUE THREAD

**Issue by Kierancraft** [al132mc/alchemistry#108]
i want this to be simpler for the basic user so i request that a command is added for /crafttweaker  create recipe [whatever u want it to craft on] and it opens a window of that thing that u click on each square to select ore dict manes or specific item(s)for the recipe and it makes that in2 a recipe script that u can paste in or something

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
