### ISSUE TITLE
Some recipes require more items than can fit in a slot in the Chemical Combiner

### ISSUE THREAD

**Issue by AranaiRa** [al132mc/alchemistry#109]
Version is 1.14.

Some recipes, like Lapis Ore, cannot be made in the Chemical Combiner because they require more items than can fit in a slot.

**Comment by ghost** [comment]
Lapis ore (or any other ore) isn't even supposed to be craftable in the combiner... probably a mistake in the port that i'll have to sort out

**Comment by ghost** [comment]
Removed lapis ore & lapis block combiner recipes in v1.14.4-8, thank you
