### ISSUE TITLE
Cannot create custom recipe for items that require item data

### ISSUE THREAD

**Issue by finalsabbath** [al132mc/alchemistry#11]
Trying to create a recipe for Actually Additions Black Quartz

Recipe

![image](https://user-images.githubusercontent.com/40742722/42384369-c939bf3e-8107-11e8-98ce-e5e95301308a.png)

Result

![image](https://user-images.githubusercontent.com/40742722/42384350-bb190892-8107-11e8-8f05-6f7b6c21d5c3.png)

Versions
MC 1.12.2
Forge 14.23.4.2729
Alchemistry 0.7.11

**Comment by al132mc** [comment]
In the current version this is possible by indicating a meta attribute.
<item meta="5">actuallyadditions:item_misc</item>

However, I just added this feature in my development version for the next release so that you can either use the meta tag or use the "minetweaker format" like you used above.

**Comment by finalsabbath** [comment]
Thanks.  Meta tag worked like a charm
