### ISSUE TITLE
[MC v1.12.2/Alchem v1.0.35] Could CraftTweaker's Combiner.addRecipe support IIngredient?

### ISSUE THREAD

**Issue by solarshado** [al132mc/alchemistry#110]
Sorry if you're not supporting 1.12 anymore, but I'm trying to add a combiner recipe with oreDict support for input. I know I can loop over the oreDic entries in ZenScript and add each individual recipe, but that seems messy.

**Comment by ghost** [comment]
I will most likely not be making any more changes to 1.12.2 at this point

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
