### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by onlyToXic** [al132mc/alchemistry#111]
this bug lets you use only 1 stack out of the 8 or more stacks that you need for an item. like a diamond

**Comment by ghost** [comment]
Can you please let me know which version of minecraft and which version of the mod you are experiencing this with?

**Comment by onlyToXic** [comment]
i am using the newest version for minecraft 1.14.4

**Comment by MLMII** [comment]
The bug also exists in 1.15.1

**Comment by asimenio-asteri** [comment]
Bug is fixed if you set the target recipe to Diamond.

**Comment by ghost** [comment]
I can confirm this bug, sorry for the late response for such a critical bug. Hopefully I can get this sorted out very soon.

**Comment by ghost** [comment]
This bug should now be fixed in 1.14.4-9 and 1.15.2-3, thank you for reporting
