### ISSUE TITLE
The game continually crashes

### ISSUE THREAD

**Issue by TroubledPlays** [al132mc/alchemistry#112]
The Minecraft launcher crashes trying to load from the Twitch folder

**Comment by TroubledPlays** [comment]
I do have a log

**Comment by TroubledPlays** [comment]
Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\gamer_pc0dgfp\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

**Comment by ghost** [comment]
This is unrelated to the mod, but i've heard people say if you go to that URL, download the file and put it in the Path specified that it should fix this issue.
