### ISSUE TITLE
Fusion Controller flexible behavior suggestion

### ISSUE THREAD

**Issue by NoX-programer** [al132mc/alchemistry#114]
To automate fusion crafts with 2 identical ingredients like H+H=He etc. using Integrated Crafting I need to invent something incredible (and, therefore, incredibly unstable) because its Crafting Interface always put identical ingredients in same slot and Fusion isn't crafting. So I have that possible offers to make Fusion smarter and solve the autocraft task:
* make Fusion to accept Slot Filler and when Slot Filler is in Fusion input slot and N>=2 ingredients in another, Fusion is crafting
* add a button to Fusion interface to switch it's mode, so Fusion takes ingredients even from single slot when there is enough (N>=2) ingredients (and, ofcourse, from two slots when them contains correct ingredients)
* another implementation of "special mode" when Fusion is not allowing more than 1 item per input slot, therefore, Integrated Crafting (or whatever) will fill both input slots itself
* or Fusion in that mode may not restrict inputs to 1, but Fusion itself will spread input to both slots (something like Actually Additions / Double Crusher does, but in same tick when got input items, just instantly)

I prefer any but the first way because it's cheaper (no need to craft Slot Filler).

MC 1.12.2
Forge 14.23.5.2847
Alchemistry 1.0.35
(Volcano Block modpack)

**Comment by ghost** [comment]
I've decided to make it so the left input and right input accept items from their respective side of the machine. (i.e. you can only input items in the left slot from the left side of the machine). Output can still be taken from any side except the left or right. This is now available in v. 1.12.2-39, and should be coming to 1.14.4 & 1.15.2 shortly.

**Comment by NoX-programer** [comment]
I remember only one mod with support of 2 item destinations on autocraft - it is Logistics Pipes. Correct me if I wrong, but Integrated Crafting, Refined Storage, Applied Energistics 2 is not supporting this feature. Well, finally, at least, Fusion Controller now can be automated by Logistics Pipes.

**Comment by ghost** [comment]
That's an unfortunate limitation for what is essentially a vanilla mechanic (i.e. vanilla furnaces). Maybe i'll fix it in the future, but this is a bit frustrating in any case...

**Comment by natedogith1** [comment]
The sided behavior seems to have been reverted in version 41.  Would it be possible to get that back?  It seems necessary to automate fusion of two different elements (otherwise I'm not sure how to prevent one element from filling both slots).

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
