### ISSUE TITLE
Suggestion for alchemistry

### ISSUE THREAD

**Issue by SniperTower** [al132mc/alchemistry#115]
Hello,

It would be very cool if you add more chemicals or even alchemistry expansion if its possible.

**Comment by matthewjessee16** [comment]
An element constructor like the one in bedrock education edition

**Comment by matthewjessee16** [comment]
We need more chemicals and compounds

**Comment by ghost** [comment]
It's hard to fulfill this request without specific suggestions. If anyone have specific ideas I will be more likely to add them.

**Comment by astro-info** [comment]
Add more connections for the electrolyzer; Example ClPb -> Cl + Pb. And add the process of growing crystals.

**Comment by ghost** [comment]
PbCl is not on 1.12 and I do not plan on adding new compounds to the 1.12 version, in addition the electrolyzer is not in 1.14+ versions. Anyway, if anyone has specific recipe suggestions for existing compounds in 1.12 or new compounds in 1.16+ you can create a new issue.
