### ISSUE TITLE
Eating KCN crashes the game: NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V

### ISSUE THREAD

**Issue by RisingInIris2017** [al132mc/alchemistry#117]
#### Mod version:

alchemistry-1.0.36

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using [CatServer-a38f3e1-universal](https://github.com/Luohuayu/CatServer/releases/tag/20.01.31)

#### Installed mods:
You may have a look on the crash-report attached below.

#### How to reproduce:
1. Eat Potassium Cyanide. 
2. Game crashes.

#### Link to full crash log:
https://paste.ubuntu.com/p/FPtffPmqvR/

**Comment by ghost** [comment]
Seems to be the same crash that happened in 1.14 a while ago, I just forgot to backport the change (or didn't think it would affect 1.12). I'll try to get this fixed up soon.

https://github.com/al132mc/chem-lib/issues/5

**Comment by ghost** [comment]
Ok, should be fixed in v1.0.38, thank you for reporting.
