### ISSUE TITLE
zh_cn translation file

### ISSUE THREAD

**Issue by xhz313123** [al132mc/alchemistry#12]
tile.electrolyzer.name=电解机
tile.chemical_dissolver.name=化学溶解机
tile.chemical_combiner.name=化学化合机
tile.evaporator.name=蒸发机
tile.atomizer.name=雾化器

item.alchemistry:mineral_salt.name=岩盐
item.alchemistry:fertilizer.name=肥料

item.alchemistry:element_hydrogen.name=氢
item.alchemistry:element_helium.name=氦
item.alchemistry:element_lithium.name=锂
item.alchemistry:element_beryllium.name=铍
item.alchemistry:element_boron.name=硼
item.alchemistry:element_carbon.name=碳
item.alchemistry:element_nitrogen.name=氮
item.alchemistry:element_oxygen.name=氧

item.alchemistry:element_fluorine.name=氟
item.alchemistry:element_neon.name=氖
item.alchemistry:element_sodium.name=钠
item.alchemistry:element_magnesium.name=镁
item.alchemistry:element_aluminum.name=铝
item.alchemistry:element_silicon.name=硅
item.alchemistry:element_phosphorus.name=磷
item.alchemistry:element_sulfur.name=硫
item.alchemistry:element_chlorine.name=氯
item.alchemistry:element_argon.name=氩
item.alchemistry:element_potassium.name=钾
item.alchemistry:element_calcium.name=钙
item.alchemistry:element_scandium.name=钪
item.alchemistry:element_titanium.name=钛
item.alchemistry:element_vanadium.name=钒
item.alchemistry:element_chromium.name=铬
item.alchemistry:element_manganese.name=锰
item.alchemistry:element_iron.name=铁
item.alchemistry:element_cobalt.name=钴
item.alchemistry:element_nickel.name=镍
item.alchemistry:element_copper.name=铜
item.alchemistry:element_zinc.name=锌
item.alchemistry:element_gallium.name=镓
item.alchemistry:element_germanium.name=锗
item.alchemistry:element_arsenic.name=砷
item.alchemistry:element_selenium.name=硒
item.alchemistry:element_bromine.name=溴
item.alchemistry:element_krypton.name=氪
item.alchemistry:element_rubidium.name=铷
item.alchemistry:element_strontium.name=锶
item.alchemistry:element_yttrium.name=钇
item.alchemistry:element_zirconium.name=锆
item.alchemistry:element_niobium.name=铌
item.alchemistry:element_molybdenum.name=钼
item.alchemistry:element_technetium.name=锝
item.alchemistry:element_ruthenium.name=钌
item.alchemistry:element_rhodium.name=铑
item.alchemistry:element_palladium.name=钯
item.alchemistry:element_silver.name=银
item.alchemistry:element_cadmium.name=镉
item.alchemistry:element_indium.name=铟
item.alchemistry:element_tin.name=锌
item.alchemistry:element_antimony.name=锑
item.alchemistry:element_tellurium.name=碲
item.alchemistry:element_iodine.name=碘
item.alchemistry:element_xenon.name=氙
item.alchemistry:element_cesium.name=铯
item.alchemistry:element_barium.name=钡
item.alchemistry:element_lanthanum.name=镧
item.alchemistry:element_cerium.name=铈
item.alchemistry:element_praseodymium.name=镨
item.alchemistry:element_neodymium.name=钕
item.alchemistry:element_promethium.name=钷
item.alchemistry:element_samarium.name=钐
item.alchemistry:element_europium.name=铕
item.alchemistry:element_gadolinium.name=钆
item.alchemistry:element_terbium.name=铽
item.alchemistry:element_dysprosium.name=镝
item.alchemistry:element_holmium.name=钬
item.alchemistry:element_erbium.name=铒
item.alchemistry:element_thulium.name=铥
item.alchemistry:element_ytterbium.name=镱
item.alchemistry:element_lutetium.name=镥
item.alchemistry:element_hafnium.name=铪
item.alchemistry:element_tantalum.name=钽
item.alchemistry:element_tungsten.name=钨
item.alchemistry:element_rhenium.name=铼
item.alchemistry:element_osmium.name=锇
item.alchemistry:element_iridium.name=铱
item.alchemistry:element_platinum.name=铂
item.alchemistry:element_gold.name=金
item.alchemistry:element_mercury.name=汞
item.alchemistry:element_thallium.name=铊
item.alchemistry:element_lead.name=铅
item.alchemistry:element_bismuth.name=铋
item.alchemistry:element_polonium.name=钋
item.alchemistry:element_astatine.name=砹
item.alchemistry:element_radon.name=氡
item.alchemistry:element_francium.name=钫
item.alchemistry:element_radium.name=镭
item.alchemistry:element_actinium.name=锕
item.alchemistry:element_thorium.name=钍
item.alchemistry:element_protactinium.name=镤
item.alchemistry:element_uranium.name=铀
item.alchemistry:element_neptunium.name=镎
item.alchemistry:element_plutonium.name=钚
item.alchemistry:element_americium.name=镅
item.alchemistry:element_curium.name=锔
item.alchemistry:element_berkelium.name=锫
item.alchemistry:element_californium.name=锎
item.alchemistry:element_einsteinium.name=锿
item.alchemistry:element_fermium.name=镄
item.alchemistry:element_mendelevium.name=钔
item.alchemistry:element_nobelium.name=锘
item.alchemistry:element_lawrencium.name=铹
item.alchemistry:element_rutherfordium.name=鑪
item.alchemistry:element_dubnium.name=𬭊
item.alchemistry:element_seaborgium.name=𬭳
item.alchemistry:element_bohrium.name=𬭛
item.alchemistry:element_hassium.name=𬭶
item.alchemistry:element_meitnerium.name=鿏 

item.alchemistry:compound_cellulose.name=纤维素
item.alchemistry:compound_aluminum_oxide.name=氧化铝
item.alchemistry:compound_magnesium_oxide.name=氧化镁
item.alchemistry:compound_potassium_nitrate.name=硝酸钾
item.alchemistry:compound_silicon_dioxide.name=二氧化硅
item.alchemistry:compound_potassium_chloride.name=氯化钾
item.alchemistry:compound_sodium_chloride.name=氯化钠
item.alchemistry:compound_water.name=水
item.alchemistry:compound_kaolinite.name=高岭石
item.alchemistry:compound_protein.name=蛋白质
item.alchemistry:compound_iron_oxide.name=氧化铁
item.alchemistry:compound_sucrose.name=蔗糖
item.alchemistry:compound_calcium_carbonate.name=碳酸钙
item.alchemistry:compound_phosphate.name=磷酸根
item.alchemistry:compound_hydroxide.name=氢氧根
item.alchemistry:compound_hydroxylapatite.name=羟磷灰石
item.alchemistry:compound_carbonate.name=碳酸盐
item.alchemistry:compound_strontium_carbonate.name=碳酸锶

item.alchemistry:condensed_milk.name=炼乳
item.alchemistry:compound_beryl.name=绿柱石
item.alchemistry:compound_starch.name=淀粉
item.alchemistry:compound_psilocybin.name=裸头草碱
item.alchemistry:compound_cucurbitacin.name=葫芦素
item.alchemistry:compound_zinc_oxide.name=氧化锌
item.alchemistry:compound_cobalt_aluminate.name=铝酸钴
item.alchemistry:compound_triglyceride.name=甘油三酸酯
item.alchemistry:compound_lead_iodide.name=碘化铅
item.alchemistry:compound_urea.name=尿素
item.alchemistry:compound_ammonium.name=铵
item.alchemistry:compound_diammonium_phosphate.name=磷酸氢二铵
item.alchemistry:compound_amide.name=酰胺
item.alchemistry:compound_ethanol.name=乙醇
item.alchemistry:compound_potassium_carbonate.name=碳酸钾

jei.combiner.name=化学化合机
jei.dissolver.name=化学溶解机
jei.electrolyzer.name=电解机
jei.evaporator.name=蒸发机
jei.atomizer.name=雾化器

itemGroup.alchemistry=Alchemistry

**Comment by al132mc** [comment]
For the upcoming release I decided to try and get rid of all of the hard-coded english strings in other parts of the mod i.e. the GUI and JEI. 

If you could also provide me with the following translations then I will include the entire thing in the next version

```
item.alchemistry:fertilizer.tooltip=Can be used like bonemeal
tile.evaporator.tooltip=Operates 50% slower in non-dry biomes

tile.combiner.unlock_recipe=Unlock Recipe
tile.combiner.lock_recipe=Lock Recipe
tile.combiner.pause=Pause
tile.combiner.resume=Resume
tile.combiner.target=Target

jei.electrolyzer.electrolyte=Electrolyte
jei.electrolyzer.consumption_probability=Consumption Probability
jei.dissolver.relative=Relative
jei.dissolver.absolute=Absolute
jei.dissolver.type=Type
jei.dissolver.rolls=Rolls
```

**Comment by xhz313123** [comment]
item.alchemistry:fertilizer.tooltip=可以当做骨粉使用
tile.evaporator.tooltip=在非干燥环境中速度减缓50%

tile.combiner.unlock_recipe=解锁配方
tile.combiner.lock_recipe=锁定配方
tile.combiner.pause=暂停
tile.combiner.resume=继续
tile.combiner.target=对象

jei.electrolyzer.electrolyte=电解质
jei.electrolyzer.consumption_probability=耗尽几率
jei.dissolver.relative=关系
jei.dissolver.absolute=完全
jei.dissolver.type=种类
jei.dissolver.rolls=转动

**Comment by al132mc** [comment]
All of these translations have been added to v0.7.13 which is up on curse.

**Comment by al132mc** [comment]
If you want to update the translations please make a new issue or PR
