### ISSUE TITLE
Evaporator crashes when water is put in.

### ISSUE THREAD

**Issue by mg-carlos** [al132mc/alchemistry#120]
On latest version (`alchemistry-1.15.2-5`), placing an evaporator down on savannah biome and adding one bucket of water immediately crashes the game. 

Using Forge 31.1.0 for Minecraft 1.15.2

**Comment by ghost** [comment]
Please provide a crash log

**Comment by mg-carlos** [comment]
I'm looking for a log but I can't find it. Looked in minecraft/crash-reports and minecraft/logs.
Is there any other place I should look? Or any other way to force one to be generated?

**Comment by ghost** [comment]
``logs/latest.log`` should work, but only if the game crashed the last time it was open

**Comment by mg-carlos** [comment]
Alright, here's the file: [latest.log](https://github.com/al132mc/alchemistry/files/4229068/latest.log)

And I noticed that to repro the crash, you add the water and then try and open the evaporator.

Let me know if there's any more info I can provide and thanks for looking into the issue.

**Comment by ghost** [comment]
That log wasn't quite as helpful as I had hoped, but could you try this dev version and let me know if it's fixed?
[alchemistry-1.15.2-6-test.zip](https://github.com/al132mc/alchemistry/files/4229176/alchemistry-1.15.2-6-test.zip)

(please unzip the .jar from the .zip file, I can't directly upload .jar files)

**Comment by mg-carlos** [comment]
Tried it just now but the issue is still there. Is there any way to add like an exception handler to see the stack trace?

**Comment by ghost** [comment]
Perhaps try providing ``debug.log`` if it's in the logs folder

**Comment by ghost** [comment]
Also, try updating your forge version

**Comment by mg-carlos** [comment]
Updated to latest version of forge (31.1.14), issue still there.

Here's the debug file: 
[debug.log](https://github.com/al132mc/alchemistry/files/4229229/debug.log)

**Comment by ghost** [comment]
I no longer am supporting 1.15, and this should be fixed in 1.16
