### ISSUE TITLE
Can’t get liquid oxygen out of Liquifier?

### ISSUE THREAD

**Issue by GamerMomB** [al132mc/alchemistry#121]
I tried using bucket, Galacticraft tanks and machines, fluid pipes (Galacticraft and Ender is) sneak clicking with bucket... nothing works. What am I missing?

**Comment by ghost** [comment]
I have no idea, i've never had anyone report this issue before. Could you give me as much information as you can? Which version of the mod? Which version of MC? How much fluid is in the liquifier?

**Comment by GamerMomB** [comment]
It was just below the limit at 9833 (give or take). I’m using 1.12. I think it’s the newest version of the mod, part of Crackpack 3 which just updated. After the O2 is liquified it is recognized as oxygen gas for Galacticraft Core. When I’m looking at the machine it says there is liquid oxygen in it. This is why I tried Galacticraft tanks, tho I’m sure that’s a compatibility issue there. I was hoping to use the oxygen since I have so much from breaking down elements, for Galacticraft oxygen tanks.

**Comment by YeOldeDog** [comment]
I'm having this issue as well, but with the Atomizer. Filled it up with milk, wrongly thought that was what to do for the quest. Tried emptying it with ExtraUtilities 2 transfer pipes + fluid ducts into an EnderIO Fluid Tank, thermodynamics servos, buckets, picking up with a pickaxe and placing it back down, but none of these got the milk out. Ended up making a new Atomizer but figured I'd submit this issue.
Using 1.12 and the modpack Material Energy^5: Entity.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
