### ISSUE TITLE
1.15.2 Liquifier not emptying

### ISSUE THREAD

**Issue by Patedj** [al132mc/alchemistry#122]
I'm currently experiencing a lot of difficulty figuring out how to empty the water from the liquifier. I've tried shift clicking with an empty bucket, downloading other mods for their fluid tranfers, tried every connection and direction possible, with no result. Putting H2O will produce the liquid form, but I cannot by all means, utilise, nor remove it.
I'm using the 1.15.2 version.

**Comment by portega** [comment]
On Volcano Block 1.0.37, you can put milk in it, but there's no recipe to process it and you can't extract it.

**Comment by Iplay2L8** [comment]
On Material Energy ^5 : Entity blood can be added but not removed

**Comment by ghost** [comment]
I no longer plan on supporting 1.15, but this has been fixed in 1.16, thank you for reporting.
