### ISSUE TITLE
1.14.4 Combiner Not Working If Different Recipe Having Same Shape

### ISSUE THREAD

**Issue by ghost** [al132mc/alchemistry#123]
CO, CO2 and CO3 recipes are the same shape, so only CO2 can be crafted.
Acetic acid, Cellulose, Triglyceride and Cucurbitacin recipes are the same shape, so only Cellulose can be crafted

![image](https://user-images.githubusercontent.com/62117547/76562043-6cb99980-649c-11ea-8f87-41079d343da1.png)
CO
![image](https://user-images.githubusercontent.com/62117547/76562059-73e0a780-649c-11ea-9dbd-508714419f48.png)
CO2
![image](https://user-images.githubusercontent.com/62117547/76561698-b8b80e80-649b-11ea-8c19-238959a00519.png)
CO3

![image](https://user-images.githubusercontent.com/62117547/76562176-b5715280-649c-11ea-9f07-ec2ca71169cb.png)
Acetic Acid
![image](https://user-images.githubusercontent.com/62117547/76562187-bd30f700-649c-11ea-87aa-00001c4ca83b.png)
Cellulose
![image](https://user-images.githubusercontent.com/62117547/76562119-95419380-649c-11ea-860d-781822ba7634.png)
Triglyceride
![image](https://user-images.githubusercontent.com/62117547/76562099-8955d180-649c-11ea-9118-2b684497d14c.png)
Cucurbitacin

**Comment by Patedj** [comment]
Are the locked recipe different? Could it only be locked to co2 being crafted? You seem to know what you are doing. Just trying to get more info.

**Comment by ghost** [comment]
This issue is legitimate, I just need to change the recipes so they don't clash like this.

**Comment by tryolivier** [comment]
Have you change the reciepe now ? I have the same problem 

https://github.com/al132mc/alchemistry/issues/127

thanks ;)

**Comment by DracoNocte** [comment]
> This issue is legitimate, I just need to change the recipes so they don't clash like this.

There's no necessary need to change the recipes. A system that let you choose easily which compound you want to produce when there are multiple outputs possible may also be fine!

For example :
![image](https://user-images.githubusercontent.com/48014879/90333481-5fae5280-dfc6-11ea-828f-837109b78b2a.png)

**Comment by ghost** [comment]
@DracoNocte  I don't think I will add enough compounds to justify the dev time it would take to tinker with the fragile combiner code to add anything like a multiple output system unless there is a big overhaul in the mod in the future

I no longer support version 1.14, but these have all been fixed in 1.16.4-4, thank you for reporting
