### ISSUE TITLE
1.15.2 CO3 don't craft

### ISSUE THREAD

**Issue by tryolivier** [al132mc/alchemistry#127]
Hello =) thanks to read this,

I try to make Co3 with 1C and 3O but it makes Co2 and let 1O

Thanks to help me =)

**Comment by rylpeck** [comment]
Same issue here

**Comment by SwanX1** [comment]
The mod takes the least resource recipe first, meaning you'd have to add the recipe through JEI and lock it.

**Comment by magic0whi** [comment]
> The mod takes the least resource recipe first, meaning you'd have to add the recipe through JEI and lock it.

It don't work

**Comment by SwanX1** [comment]
CO3 also isn't even chemically possible?

**Comment by magic0whi** [comment]
> CO3 also isn't even chemically possible?

Yes, even if I use JEI to lock the crafting, it just does not output the CO3.
Current the only way to get CO3 is to decompose existing compounds.

**Comment by leoXplod** [comment]
Same here too!!!


AwanX1, you are right, it is not really posible, 'cause it is an ion, but for minecraft purposes this crafting helps a lot, for farming redstones for example.

**Comment by DracoNocte** [comment]
~~It is possible to craft CO<sub>3</sub> **if** you're playing with JEI. You can use the "Move Items" button of JEI, which will lock the recipe you want into the Chemical Combiner. Then you can put your items in in order those to be combined.~~

~~**However**, it seems indeed to be a problem when not playing with JEI.~~

*Edit:* I just noticed there are other references of this problem, #94 and #123 (this one's tagged as a bug).

**Comment by ghost** [comment]
I am no longer supporting 1.15, but this has been fixed in 1.16.4-4, thank you for reporting.
