### ISSUE TITLE
Fusion and Fission Multiblock loading error

### ISSUE THREAD

**Issue by kornfan6589** [al132mc/alchemistry#128]
On server start, errors are thrown relating to the fusion and fission multiblocks. does not crash and the multiblocks do function, but likely causing unnecessary overhead in server start up, and potentially while machines are in use. 

Log of server loading; clipped for relevance

https://pastebin.com/kcuRivpu

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
