### ISSUE TITLE
"Liquifier" not updating correctly in JEI

### ISSUE THREAD

**Issue by w1zdom** [al132mc/alchemistry#129]
![image](https://user-images.githubusercontent.com/65294676/81823766-3e713c80-9567-11ea-95e5-53588f6a247d.png)

There appears to be some issue with the Liquifier in JEI, when looking at available recipes that use the liquifier, at the top of the window it is spelt as the Liqufier instead, as shown in the image.

Probably a simple fix (issue was spotted in Antimatter Chemistry 1.2.31, Twitch Launcher)

**Comment by ghost** [comment]
Just a small typo in the .lang file, thanks

https://github.com/al132mc/alchemistry/blob/1.12.2/src/main/resources/assets/alchemistry/lang/en_us.lang#L332
