### ISSUE TITLE
Automation Configuration [Suggestion]

### ISSUE THREAD

**Issue by Rsslone** [al132mc/alchemistry#130]
In my modpack I seen the crazy stuff people do with this mod, its such a cool mod but easily broken when you can automate it. The old minechem I believe had a option to disable automation with the blocks. Can this be a thing?

**Comment by Rsslone** [comment]
friendly poke :)

**Comment by ghost** [comment]
Was there a particular version you wanted me to target first? (i.e. 1.12.2 or 1.16.x)?

**Comment by Rsslone** [comment]
1.12.2 :)

**Comment by ghost** [comment]
This has been added in 1.12.2-42 which I just released, thank you for the suggestion.

**Comment by Rsslone** [comment]
You're a boss, thank you!
