### ISSUE TITLE
Great Idea [Elements burn colored flames]

### ISSUE THREAD

**Issue by leoXplod** [al132mc/alchemistry#131]
Hello, first of all I apologize for maybe not be using the correct place to report my idea to the mod developer(s), but here I go:

I'm chemistry teacher and minecraft lover too. I played the alchemistry mod the last 6 months an I found in it a very big potential in using for educational purposes, like classes or so.
But, I have some ideas to modify some aspects in the mod (like crafting recipes or more recipes). That allows explore more concepts related to chemistry using pedagogic strategies. Then, I see an oportunity to maybe whrite cientific articles in the education area, of course if you have interest. Cientific article carries the name of the autors of the mod, what do you think?

Now an extra idea: when the player drop some elements in the world and set them in fire, the fire acquires colors respecting the colors of "the flame experiment", a classic experiment in the chemistry lessons. Write "flame experiment" on the google and search for some images you will understand what I mean if already dont so.

Well, write me.
Waiting for answer(s).

leoXplod

**Comment by skiller8641** [comment]
like if you trow salt or other reactive it would change for a modded fire? like purple or yellow, just asking.

**Comment by skiller8641** [comment]
i made the procedure but with my element, not the alchemestry one so it have to be replace
[chemestry_fire.zip](https://github.com/al132mc/alchemistry/files/7874993/chemestry_fire.zip)
.

**Comment by Dark-Arcana** [comment]
I'm planning to add this feature to some chemicals in ChemLib. Since this is ChemLib related and not Alchemistry, I'm closing this issue.
