### ISSUE TITLE
Dissolver Types Absolute/Relative.

### ISSUE THREAD

**Issue by AefRal** [al132mc/alchemistry#132]
In the Dissolver Jei for Pulverized Iron, 

the first page shows 
Type: Relative
Rolls: 1
Chance --- Output
100% --- 16 Iron Element,

The second page shows
Type: Absolute
Rolls: 1
Chance --- Output
25% --- 4 Gold Element
25% --- 4 Tin Element
25% --- 4 Nickel Element
25% --- 4 Silver Element

I've looked everywhere I could think of.
I've seen no documentation on how to switch types.
It always makes the 16 Iron Element.
Tried applying a redstone signal, no change.
Types aren't even mentioned on the wiki.

How can I change between them?

**Comment by ghost** [comment]
Are you playing a modpack? There is a recipe clash apparently and whoever the author of the modpack is (if not yourself) needs to fix that. You are unable to switch between them.

**Comment by AefRal** [comment]
I see. Thank you.
I'm playing Material Energy 5^ Entity by Geninja_San via Twitch app.
