### ISSUE TITLE
Request 1.16.1

### ISSUE THREAD

**Issue by Ibirtem** [al132mc/alchemistry#133]
I guess the issue speaks for itself. Hope your wonderful mod will come out soon!

**Comment by ghost** [comment]
I think it's mostly(?) done, but I still need to figure out a few things first.

**Comment by Mingu2209** [comment]
Hi! I see that you know published for 1.16.3. Are you going to release it in 1.16.1? That would be amazing!! Thanks a lot in advance

**Comment by ghost** [comment]
Yes, I have released it for 1.16.3, but I only plan on supporting the most recent version (in this case, 1.16.3)
