### ISSUE TITLE
random useful suggestion hope u will see [Fusion enhancements]

### ISSUE THREAD

**Issue by hen87people** [al132mc/alchemistry#140]
alchemistry mod suggest(most is for element and fusion mutiblock thing)
***realistic of fusion and element***
make the fusion element be more realistic like in real
there is only a very small chance by getting a atom like oganesson so let the fusion have chance to get like real life
(more block 
i suggest add some random block like atom detector like it can detect the element u make, u can use in quest thing maybe)
**fusion chance**
and add some thing like use different element have different chance by getting successed fusion like most heavy element start as 110 is use calcium-48 and some random uran neptun pluton americium ect
make thing like this 
(more and more new blocks maybe)
add some more block like atom speeder and target setter because in real life you need a target to let the speed atom to hit different speed have different effect like too fast will become nothing and too slow and also nothing happend or a very low chance get success fusion 
**some random real fusion recipe**
add some spicial fusion recipe like get a U-238 and 15 neutron fusion and get a 253 einstenium and 7 neutorn get shot away or 206-Pb+ 54-Cr to get 257-Sg thing otherwise player just can use hydrogen and stack up things
**isotope**
and most important thing is add isotope of element and nature decay of radioisotop (u might ask if add decay what about the extreme short half live element/isotope such as hydrogen-7 or oganesson, the atom detector is useful in this thing , and how to collect the element? you might ask. so to collect the element add someting like time slower to slow down the decay of element
**more random thing thing i suggest**
chance the fusion controller slots into a more place to place the element
original is 2 slots(of element)->1 slots(of element)
new is add more slot like under cus the element have decay so the heavy element will fast decay into small piece so add more area to place the element 
just good 
and if u want add decay make sure to add the decay also active in chest and storage area(the drawer idk lol)
and i want suggest to you so i create a new account so im new in github
i successed waste 1 hr in my life and hope you can do them all and ik the coding is hard and will die lol 
have a nice day and good luck

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
