### ISSUE TITLE
I would love to be able to speed up my fission/fusion times.

### ISSUE THREAD

**Issue by DigitalMonkeyMaster** [al132mc/alchemistry#142]
Hey I'm currently playing the Anti-matter Chemistry mod pack and I am LOVEING it SO much.
I've got my base all set up and I'm in the process of automating the breakdown of things that produce useful elements and compounds such as wheat (cellulose and starch), beetroot and I have my cobblestone being dissolved at an astonishing rate.
Now I'm in a situation where the reactors are actually slowing me down. I'm breaking up common elements such as oxygen and combining other elements to automate the acquisition of metals really easily and this is great.

I know the obvious answer is to just build some more reactors however with the cost of construction and the sheer size of the machines themselves I don't want to be littering my world with these big ugly machines! (no offence)

I would make one of 2 suggestions that would remedy this issue for me;
1.) Be able to craft and install upgrades such as; reduced time to completion at the cost of RF/tick, or other upgrades such as  RF/tick reduction
2.) Allow a fusion controller to be placed on each of the cardinal faces; This would still require the setup cost of the main structure and controller costs however you would be able to increase the output by up to 4 times (top and bottom of the controller don't really make sense to me). This would also allow for interesting challenges while automating the fission and fusion.

For now I will just go ahead and build a couple more fusion reactors but I'd love to hear your opinion on this :)
Happy Crafting :)
![2020-10-22_06 49 26](https://user-images.githubusercontent.com/73271713/96830115-cae72b80-1432-11eb-9b23-e4d9c3087fa0.png)

**Comment by MasterEnderman** [comment]
FYI: In Antimatter Chemistry the Reactors were made faster a few updates ago. :)
https://github.com/SmashingMods/antimatter-chemistry/commit/0bfcbe5f95caef0419db0d7cf1d6dfab0926e32e

**Comment by Dark-Arcana** [comment]
As of right now, you can adjust the speed in a config. I might add upgrade modules at some point in the future. The second suggestion is simply never going to work. It would be far too complicated to have multiple multiblock structures in the same block positions.
