### ISSUE TITLE
How can I disassemble compounds?

### ISSUE THREAD

**Issue by IvanTo88** [al132mc/alchemistry#143]
Hello,

I'm playing the last version of your mod Alchemistry for Minecraft 1.16.3 and I like it. However I noticed that I cannot disassemble compounds (for example, I cannot divide water - H2O - into Hydrogen and Oxygen). Is there a way to do that?

Also, it's impossible to take water back from the Liquifier machine.

Hoping to see these problems solved as soon as possible, cheers! :)

**Comment by leoXplod** [comment]
Same here too

**Comment by ghost** [comment]
Should be fixed now in 1.16.3-2. Re-open if there are still issues. Please update alib as well
