### ISSUE TITLE
1.16.3 Chemical dissolver not working on multiplayer

### ISSUE THREAD

**Issue by Theo-Winters** [al132mc/alchemistry#144]
On a server with Alchemistry the chemical dissolver won't accept any items and causes you to drop them. On single player it works fine. Basically makes getting any elements impossible.  I've tried 2 different mods to power it, making it seem it's the mod itself.

Forge version: 34.1.25
Alchemistry version: 1.16.3-1
ALib: 1.16.3-2
ChemLib: 1.16.3-1
Jei:1.16.3-7.6.0.49

**Comment by ghost** [comment]
I'm aware of this issue and have been working on a fix this last week, hopefully it will all be sorted out soon.

**Comment by leoXplod** [comment]
This hapenned to me in the single player mode, i can't decompose substances into elements.

**Comment by Theo-Winters** [comment]
Not to bother or try to rush you, but is there any word on the next update coming out soon?

**Comment by ghost** [comment]
Sorry.. i'm just not sure yet, hopefully within a week or 2.

**Comment by Theo-Winters** [comment]
No hurry, I just love this mod and I really want to add it to my pack lol. Thanks again for all your work, it's greatly appreciated!

**Comment by ghost** [comment]
This should finally be working now, new version 1.16.3-2, let me know if there are still issues.
