### ISSUE TITLE
Item Used When Opening Mod GUIs

### ISSUE THREAD

**Issue by Darkosto** [al132mc/alchemistry#145]
Hello!

Opening a GUI with an edible item in hand will cause the player to eat the item. Any use items like an ender pearl will be thrown when opening an Alchemistry GUI too. If you have an inventory item (like a backpack) it will instead open the inventory of the held item instead of your GUI. This is not a normal mechanic in vanilla GUIs or other mods so I assume it is a bug. 

MC version: 1.16.4
Java: 14.0.2
Mod version: 1.16.3-2
alib version: 1.16.3-2
chemlib: 1.16.3-1
Forge: 35.1.11

Thanks!
Darkosto

**Comment by ghost** [comment]
Thanks for reporting, hopefully i'll get a chance to investigate this soon.

**Comment by ghost** [comment]
This should be fixed by updating to the new version of alib, 1.16.3-3, re-open if you are still having issues after updating.
