### ISSUE TITLE
1.16.4 CraftTweaker / KubeJS Compatibility

### ISSUE THREAD

**Issue by VampireTechnologyLord** [al132mc/alchemistry#148]
Hi there!

I know there is a wiki for how to make custom dissolver, combiner... recipes, but everytime I am trying to reload the script, CT tells me, "member not found: alchemistry". May just be because you havent had enough time to work on this, but you also might just have forgotten it ;-).

Would really enjoy, if you could bring it back, because I really enjoy playing with your mod!

edit: I would also be happy about KubeJS compat ;-)

PS: may also be my fault, so here is the CT Script:
`mods.alchemistry.Dissolver.addRecipe(<item:minecraft:bucket>, false, 5,
[[10, <item:minecraft:stone>],
 [20, <item:minecraft:sand>, <item:minecraft:iron_ore>]]);`

Forge: 1.16.4-forge-35.1.0
Alchemistry: alchemistry-1.16.3-2
CT: CraftTweaker-1.16.4-7.0.0.63

**Comment by Freebi85** [comment]
You can make pretty easily recipes for every machine in all mods including Alchemistry with KubeJS. There is no integration required beside downloading the mod and put the scripts in the proper folders of course^^ If you need some help with this (provided you are interested in using kubejs)  you can ping me in Al's discord. -> Freebi Peers my name.

**Comment by The-Math-Fish** [comment]
Strangely enough using #loader alchemistry at the top of your script will remove the error. CraftTweaker seems to accept the scripts just fine, but they don't actually do anything. Here is the script I used, loaded as a ZS file. I would have a lot more in here, but this is where I noticed the problem pop up.

```
#loader alchemistry

mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_ammonium>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_ammonium_chloride>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_barium_sulfide>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_butane>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_cobalt_nitrate>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_diammonium_phosphate>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_ethane>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_iron_iii_nitrate>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_nickel_sulfate>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_nitric_acid>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_sodium_bisulfate>);
mods.alchemistry.Dissolver.removeRecipe(<item:chemlib:compound_strontium_hydroxide>);

mods.alchemistry.Dissolver.removeRecipe(<item:minecraft:coal_ore>);
```

EDIT: I also shut down and restarted the world to get a log in case it spit out some more information about this. I was not disappointed! There were so many WARN messages thrown by Alchemistry that the logs stopped printing them out. I added my most recent log to the files. Go about halfway down the log or search for "alchemistry".

[latest.log](https://github.com/al132mc/alchemistry/files/6291925/latest.log)

**Comment by Secretname2009** [comment]
Im running 1.16.5 with this mod along with ALib, CraftTweaker and many other mods. I tried to add a recipe for Steel Dust but the file never gets properly parsed. When the file has the line #loader alchemistry, it jumps over the file and never loads it again.
Removing that line of text makes it load the file but crafttweaker reports "No such symbol: alchemistry". I even tried replacing alchemistry with chemlib but that returned same error.

**Comment by jaredlll08** [comment]
@Freebi85 
> Although Crafttweaker would require an integration on the part of al132 or the CT devs.

This is completely false, please stop spouting this nonsense, we have had generic recipe support since 2019 (https://github.com/CraftTweaker/CraftTweaker/commit/7cb66910a8aa3020ae8aa86c7c01b4b78d52b478).

The reason we encourage explicit plugin support is because having a single line being able to add a recipe is A LOT cleaner compared to messing with the json format of the recipe, but the explicit support is not required at all.

We even have a page on the docs about it.
https://docs.blamejared.com/1.16/en/mods/other_mods

@The-Math-Fish @Secretname2009 @VampireTechnologyLord

You are using 1.12 docs for 1.16. This mod doesn't have explicit 1.16 CraftTweaker support.

You can take a look at the page I linked above, you should be able to customize this mod's recipes using the generic support, like so:

Remove recipe:
```zenscript
<recipetype:alchemistry:dissolver>.removeRecipe(<item:chemlib:compound_ammonium>);
```

Add recipe:
```zenscript

<recipetype:alchemistry:dissolver>.addJSONRecipe("unique_name", {
    input: {
        "item":  <item:minecraft:dirt>.registryName
    },
    output: {
        "rolls": 1,
        "relativeProbability": true,
        "groups": [
            {
            "probability": 1.0,
            "stacks": [
                {
                    "item": <item:minecraft:diamond>.registryName
                },
                {
                    "item": <item:minecraft:emerald>.registryName,
                    "count": 4
                }
            ]
            }
        ]
    }
});
```

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.

**Comment by YourLocalWarCriminal** [comment]
Same happened for me but with the farmer's delight cutting board recipe, and the simplest fix was to check did you write everything according to syntax, Crafttweaker tends to tell you that there is no such member as:XY, and it is usually caused by a typo in your code.
