### ISSUE TITLE
1.16.4 No Condensed Milk Recipe With Industrial Foregoing

### ISSUE THREAD

**Issue by cyberdragon442** [al132mc/alchemistry#149]
The evaporator will not accept Industrial Foregoing milk as a valid ingredient to make condensed milk.

**Comment by ghost** [comment]
I haven't figured out how to use fluid tags yet, so it is something I will need to investigate.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
