### ISSUE TITLE
[Request] Add crafttweaker support for easier adding or change recipes

### ISSUE THREAD

**Issue by Fireztonez** [al132mc/alchemistry#15]
Hello,
Thank's for your mod, this is a great mod adding somes basic thing's from Minechem on Minecraft 1.12.2, this is really nice!! Thank's for your work!

I wonder if you can add, question to simplify a lot the creation of recipes or the recipes removing, by a Crafttweaker support, like a really hight numbers of mod do already!! All the documentation for the Crafttweaker API is availiable on the Amazing Crafttweaker Wiki: https://crafttweaker.readthedocs.io/en/latest/

If you wonder why I ask for that, when you already make your own XML recipes system, here couples basics reason;
- It allow Modpack-Dev to make or recipes with a simple line, easy to edit, maintain and remember the syntax.
- It allow Modpack-Dev to use loop with array variables/global, for make big quantity of recipes easily and without making all one by one...
- It allow Modpack-Dev to make to create somes functions for more complex recipes or rules
- Support variables and global of multiples types, question easily call specific thing's.
- And lot more!!!

Fireztonez

**Comment by al132mc** [comment]
I've just finished adding this in the development version. It should be available in the next release

**Comment by al132mc** [comment]
Alright, v0.8.0 has been released with CT support. I'll add some documentation to the project wiki soon
