### ISSUE TITLE
Chemical Recipes

### ISSUE THREAD

**Issue by MegaGamer265** [al132mc/alchemistry#150]
Some elements do have the same crafting recipe! And some that exist in older versions don`t exist anymore.

**Comment by ghost** [comment]
Could you give me a list of which recipes are problematic please?

**Comment by cyberdragon442** [comment]
Seems related to https://github.com/al132mc/alchemistry/issues/149

**Comment by ghost** [comment]
Are there any other recipes? Or only that one?

**Comment by cyberdragon442** [comment]
I will have a look, but I also have Techemistry installed so some otherwise broken recipes may be added by that. However, I do notice duplicate recipes from that mod as well (IE redundant and often worse ways to make compounds outside of the combiner).

**Comment by ghost** [comment]
That is somewhat intentional. Both mods are allowed to be standalone and currently there are no conditional recipes based on if the other mod is installed, nor do I specifically have plans to do so.

**Comment by MegaGamer265** [comment]
Well this is the only mod i use with chemistry and i tried making vanilla items but another was coming out. When i remember correct it was with slime or eggs, so there might be a lot of other items that don`t work correctly. Oh and sugar has no recipe.

**Comment by cyberdragon442** [comment]
Slime has a recipe.

Eggs and sugar don't but sugarcane does.

Milk can be made but not decomposed (as I said earlier).

Redstone and glowstone only have block recipes not dust recipes.

Netherwart has no recipe.

**Comment by ghost** [comment]
I added recipes for all the things listed in the last comment in 1.16.4-1, thank you. I have not figured out how to use fluid tags yet, so #149 will remain open
