### ISSUE TITLE
/reload doesn't remove Chemical Combiner recipes (and possibly others)

### ISSUE THREAD

**Issue by Wxrlds** [al132mc/alchemistry#156]
This is mostly a summary of the Discord message history of the [Alchemistry Discord](https://discord.com/invite/4swu3fy) and the [CraftTweaker Discord](https://discord.com/invite/mYtpXwe).
Message links to the [Alchemistry History](https://discord.com/channels/458703035997224973/543932572653060105/812276987544469555) and [CraftTweaker History](https://discord.com/channels/136877912698650625/354745056743260172/812259635019907073) for more context if needed.

Replacing Chemical Combiner recipes works by either creating a datapack and by replacing the .json file on for example this path ``data/alchemistry/recipes/combiner/ingot_osmium.json`` with a custom recipe.
Another way is doing it with CraftTweaker and removing the recipe with ``<recipetype:alchemistry:combiner>.removeByName("alchemistry:combiner/ingot_osmium");`` and adding the custom recipe with ``<recipetype:alchemistry:combiner>.addJSONRecipe(...``.
Both of these methods work for removing custom recipes and both methods are not affected by the ``/reload`` command.
When adding recipes with CraftTweaker the ``/reload`` command works but if you remove the recipe from your scripts ``/reload`` doesn't change the recipes which were added with a CraftTweaker script, unless the game is restarted.

**Comment by Jordan-Cottle** [comment]
Thank you for posting this issue. I just spent the last hour going insane trying to figure out why my recipe wasn't showing up after a `/reload` and there were absolutely no errors anywhere in the logs (that would be relevant).

Turns out all I needed to do was turn it off and back on again 😅 

For what it's worth, my recipe was just a way to convert alchemistry hydrogen into mekanism liquid hydrogen using the liquifier.

```zenscript
# Convert chemlib hydrogen to mekanism hydrogen
<recipetype:alchemistry:liquifier>.addJSONRecipe("liquify_hydrogen", {
  "group": "minecraft:misc",
  "ingredient": {
    "item": "chemlib:element_hydrogen"
  },
  "inputCount": 8,
  "result": {
    "fluid": "mekanism:hydrogen",
    "amount": 250
  }
});
```

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
