### ISSUE TITLE
[Suggestion] Add mod priority list to item outputs

### ISSUE THREAD

**Issue by Wxrlds** [al132mc/alchemistry#159]
It would be nice if we would have the ability to specify what mod the item ouput is from. Immersive Engineering for example does this and helps as it unifies ores, ingots, dusts,... if Alchemistry (or Chemlib not sure who would handle that) would allow you to set a priority list ``1. Immersive Engineering, 2. Mekanism, 3. Chemlib`` every Copper Ingot made with the Chemical Combiner would become an item from Immersive Engineering, Osmium made with the Combiner would become an item from Mekanism and every Ingot that's not from those first two mods would be from Chemlib.

**Comment by ChiefArug** [comment]
Thermal and Tinkers are now on 1.16, so they should be put in the priority list. (Create might also be one to put in the list, but a Modpack with Alchemistry and Create should have at least one of the other ones mentioned)

**Comment by Dark-Arcana** [comment]
This is something that needs to be handled by modpack makers. You can easily unify using tags in kubejs or craft tweaker. Alchemistry's rewrite will start to focus on using more tags for things to make this as easy as possible for modpack makers.
