### ISSUE TITLE
[1.16.5] Locked Recipe of Chemical Combiner is cleared after game restart.

### ISSUE THREAD

**Issue by Oyami-Srk** [al132mc/alchemistry#161]
Is that a feature or designed to be? When I locked a recipe in the combiner, after restarting the game, it clears.

**Comment by ghost** [comment]
Not intentional, thank you for reporting.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
