### ISSUE TITLE
[1.16.5] Missing Chemical Dissolver Recipes & Recipe Suggestions

### ISSUE THREAD

**Issue by moon-st0ne** [al132mc/alchemistry#163]
the following vanilla Minecraft blocks/items are missing recipes for the Chemical Dissolver (some may be intentional):

- Coarse Dirt; should be identical to Dirt, maybe up the SiO2 content to reflect the integrated Gravel?
- Podzol; should be identical to Grass, maybe up the Cellulose content to reflect the thick dead leaf cover?
- Crimson Nylium; should be identical to Netherrack, added chances for Cellulose/Germanium/Selenium reflecting its Nether Wart covering?
- Warped Nylium; similar to Crimson Nylium, but something that makes it warped. maybe replace Ge/Se with small Hg/Nd chance? since it is related to Endermen/Ender Pearls
- **Gold Ore**; this is certainly a bug, should have 32x Au
- **Iron Ore**; this is certainly a bug, should have 32x Fe; notably, metal ores from other mods like Thermal Foundation are also missing now
- Nether Gold Ore; should be identical to Netherrack but the rolls for Au and nothing should be replaced with 100% 32x Au, since it is literally Gold inside Netherrack
- Sandstone; this is probably a bug, should probably just be the same as Sand
- Chiseled/Cut Sandstone; may not be necessary but could just copy Sandstone's recipe
- **Block of Gold/Block of Iron** are also both missing their recipes from before
- Smooth Quartz Block; should be identical to Block of Quartz
- Smooth (Red) Sandstone; should be identical to their sandstone type counterparts
- Smooth Stone; i have nothing for this one. it's just Stone but different.
- Brick(s); identical to Clay? it's just dried, fired Clay after all.
- _Mossy Cobblestone_ is not missing a recipe, but its recipe should probably have a chance for Cellulose
- Carved Pumpkin; should be identical to Pumpkin
- Soul Soil; should beidentical to Soul Sand
- (Polished) Basalt; i think modded basalt used to have a recipe, but if not: Wikipedia says generally 45-52% SiO2, 2-5% Sodium Oxide or Potassium Oxide (or both?), 0.5-2% TiO2 (substitute existing Titanium Oxide?), 5-14% Iron (II) Oxide, 14%+ Aluminum Oxide; also mentions ~10% Calcium Oxide and 5-12% Magnesium Oxide
- Stone Bricks & Variants; i also have nothing for this one. it's just Stone but different.
- Mycelium; Grass but throw in some Psilocybin in there since it's made of mushroom hyphae
- Cracked/Chiseled Nether Bricks; should be identical to Nether Bricks
- other Quartz variants; should be identical to Block of Quartz
- Terracotta (any color); functionally identical to Clay, but typically specifically has some type of Iron oxide; chance Iron (II) Oxide?
- Glazed Terracotta (any color); should be identical to Terracotta, but since they're so vibrantly colored, perhaps give them a chance to give their respective dye's unique compound?
- Packed Ice; this is really just Ice but denser, so either share a recipe with Ice or up its Water content
- Prismarine; this one is hard to pin down, but judging by its appearance and name it appears to be some kind of mixture of Aquamarine and something. after discussing in the discord, i'm going to suggest the following:
- Prismarine Shard: 4x Beryl, 3x Niobium, 1x Selenium
- Prismarine Crystal: 4x SiO2, 3x Phosphorus, 1x Selenium
- Prismarine: 16x Beryl, 12x Niobium, 4x Selenium
- Prismarine Bricks: 36x Beryl, 27x Niobium, 9x Selenium
- Dark Prismarine: 32x Beryl, 24x Niobium, 8x Selenium, 4x Titanium Dioxide
now then...
- Warped Wart Block; identical to Nether Wart Block but the same changes made to Warped Nylium carry over, replacing Ge and Se with Hg and Nd, at reduced rates
- Red Nether Bricks; Nether Bricks but different; should probably just be identical to Nether Bricks
- Concrete (any color); SiO2 + H2O. that's it. it's just hydrated Sand and Gravel.
- Concrete Powder (any color): SiO2, it's just fancy sand
- any Dead Coral/Fan/Block; CaCO3, that's all their hard bits are made of, and they're dead
- Tube Coral; CaCO3 + CoAl2O4
- Brain Coral; CaCO3 + As4S4 (pink dye) OR CoCO3, which is a pink cobalt-based pigment
- Bubble Coral; CaCO3 + BaCuSi2O6 (magenta dye) OR COCl2, which is a pink-purple cobalt-based pigment when hydrated
- Fire Coral; CaCO3 + HgS (red dye) OR Co(NO3)2, which is a fiery red cobalt-based pigment
- Horn Coral; CaCO3 + PbI2 (yellow dye) OR K3[Co(NO2)6] (Indian Yellow), a sulfur-yellow cobalt-based pigment
- i don't know i just really like the idea of all of the coral blocks being dyed with variations of cobalt
- Blue Ice; once again it's just Ice but even denser now. just...make it give you a ton of H2O?
- Kelp; 100% Cellulose + 17% Sodium Carbonate+ 5% Potassium Iodide (KI)
- Blackstone & co.; this is probably just another kind of Basalt, so should share the same recipe (maybe with some new trace elements?)
- Gilded Blackstone; Blackstone, but with some Gold inside; maybe 8x Au, since it can't be made into an ingot normally
- Tall Grass/Fern/Dead Bush/Sea Grass; should all just have a chance to yield Cellulose
- Sea Pickle; Cellulose and lime dye, which is CdS+Cr2O3
- All of the flowers; should yield Cellulose at least, and probably the compounds that compose the dyes they produce
- Crimson/Warped Fungus; share a recipe with Red/Brown Mushrooms, but add Se to the Crimson and Hg to the Warped
- Crimson Roots; Cellulose, small chance HgS (because they're really just red and not a form of Nether Wart)
- Warped Roots/Nether Sprouts; Cellulose, small chance CuCl2 (for a similar reason to Crimson Roots)
- Weeping/Twisting Vines; Cellulose, and probably just chance for red or cyan dye material since again, unrelated to Nether Wart
- Chorus Plant/Flower/Fruit/Popped Fruit; should contain Lutetium since that appears in Purpur, and probably some other odd things like Hafnium
- Chain; should be able to break down into Fe
- Skulls; the Wither Skeleton Skull is the only one of the four that has a recipe; now that they are able to be obtained in vanilla, they should all be given the appropriate recipes
- Bell; a way to recycle Gold from Bells would be nice
- Shroomlight; essentially an organic Glowstone, should contain glow chemicals like Phosphorus, and should probably yield Cellulose and perhaps a rarer element
- Honey Block/Honeycomb; 100% Sucrose, 100% Protein, probably also some amount of Water
- Turtle Egg; 100% Protein, 100% CaCO3
- Scute; 100% Keratin (or Protein i suppose)
- Ancient Debris, Netherite Scrap; this is a tough one. i think it's probably some form of Tungsten due to its properties, so maybe pure Tungsten? Tungsten Carbide?
- Netherite; 4x whatever Netherite Scrap is, and 64x Au
- Golden Apple; missing recipe?
- Snowball; missing recipe? 4x H2O?
- Paper; missing recipe? Cellulose?
- Book; if Paper has a recipe, Books should as well, with Cellulose and Protein
- Ink Sac; Black Dye has a recipe, but Ink Sac no longer does
- Blue Dye; since Blue Dye no longer _has_ to come from Lapis Lazuli, it should be reconfigured. probably as a copper or aluminate compound?
- Blaze Rod; originally removed for balance purposes with other mods, maybe it might be time to add a config option to enable a recipe for Blaze Rods
- Ghast Tear; i can't remember if this had a recipe before or not
- Magma Cream; same as above
- Rabbit's Foot/Rabbit Hide; both should yield Protein
- Dragon's Breath; it would be rather nice if Dragon's Breath yielded unique elements, especially noble gases
- Shulker Shell; potentially CaCO3 + whatever Purpur is? Lutetium?
- Phantom Membrane; potentially Protein + some vaguely rare element, like Cerium or something?
- Nautilus Shell; 100% CaCO3
- Heart of the Sea; frankly, not sure if this one should have a recipe, it's too strange; however, now would be another good opportunity to use never-before-used elements
- Sweet Berries; Cellulose and Sucrose
- Honeycomb; same as the Block of Honey and Honeycomb Block

i believe i got everything, at least, everything that reasonably should have a Chemical Dissolver recipe.

**Comment by ghost** [comment]
I've been procrastinating on finishing this up, but i've got maybe 20 bullet points on the list to do yet

**Comment by AnAwesomGuy** [comment]
Sorry to bother you but some more things. (I don't know how to make a bullet point.)
Sand should have a mix of all the stones.
Feather: protein?
Glass, glass panes, and glass bottles should have the same as sand.
Blue dye: C37H34N2Na2O9S3 (found this online).
Brown dye: C18H20Cl2N8 (also found this online).
Colored glass (panes): glass + the respective dye formula.
Book and quill: ink sac + book + feather.
Edit: also everything should be makeable through the chemical combiner.
(That's all I could think of.)

**Comment by ghost** [comment]
> 
> 
> Sorry to bother you but some more things. (I don't know how to make a bullet point.)
> Sand should have a mix of all the stones.
> Feather: protein?
> Glass, glass panes, and glass bottles should have the same as sand.
> Blue dye: C37H34N2Na2O9S3 (found this online).
> Brown dye: C18H20Cl2N8 (also found this online).
> Colored glass (panes): glass + the respective dye formula.
> Book and quill: ink sac + book + feather.
> Edit: also everything should be makeable through the chemical combiner.
> (That's all I could think of.)

Feather and glass already have recipes, I don't think I will do a recipe for books because even vanilla has multiple recipes, though I may change my mind later. As for the dyes, I may change them in the future but for right now i'm not going to.

**Comment by ghost** [comment]
Added most/all of these in 1.16.5-1, thank you! If there are any errors or changes you think that should be made please create a new issue.

**Comment by AnAwesomGuy** [comment]
oh i didn't see those sorry
