### ISSUE TITLE
Evaporator Shows wrong recipe in Guide Book

### ISSUE THREAD

**Issue by ChiefArug** [al132mc/alchemistry#164]
![image](https://user-images.githubusercontent.com/73862885/113826103-e4f4aa80-97d5-11eb-90b9-0e3749580b41.png)
The evaporator has the wrong recipe in the patchouli guide book, it shows the recipe of the atomizer instead.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
