### ISSUE TITLE
Neutrons, Protons, Electrons, and Atoms?

### ISSUE THREAD

**Issue by GuidingLichYT** [al132mc/alchemistry#166]
Im a nerd for chemistry, and i was wondering if you could make a Neutron, Proton, Electron, and Atoms update?
If you think this is a good idea, i can help you with the atom stuff. If you want to contact me. Do it in discord at 
"The Guiding Lich#6618" (just coy and past inside the quotes)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
