### ISSUE TITLE
Two Iron Oxides, both not fully working as intended

### ISSUE THREAD

**Issue by JadeKaiser** [al132mc/alchemistry#169]
In the 1.16.5 version there are currently two separate "iron oxide" compounds. There is "Iron(II) Oxide," composed of 1 iron and 1 oxygen. There is also "Iron Oxide," composed of 2 iron and 3 oxygen. The former is not used for any recipes whatsoever in the Chemical Combiner, and the latter fails to work if you try to make it in the Chemical Dissolver (even with a locked recipe).

I'm pretty sure that the first one (1 iron 1 oxygen) isn't supposed to exist, and needs to be purged with extreme prejudice. Meanwhile, the second one needs to be fixed so that it can be made in the Chemical Combiner instead of only being obtainable by dissolving something that gives it directly. Based on my (admittedly limited) knowledge of programming, I suspect that purging the imposter might fix the intended one all its own, but that's just a suspicion.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.

**Comment by JadeKaiser** [comment]
Well, good to finally hear back about it at least. Maybe not my place, but I would request that you consider back-implementing a new 1.16 version of the mod eventually, as 1.16 does retain a section of the modding community which chose never to update past it for various reasons. Whether those be compatibility issues, desire to farther refine the existing state of their mods first, or packs wanting to make use of other mods that never updated past it or are no longer supported. Sort of like with 1.12 on a smaller scale.
Up to you of course and obviously, even if you do decide to do so you should focus on the current version first. Just something to consider.
