### ISSUE TITLE
Every machine except the dissolver use energy for 1 tick longer than stated in the config

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [al132mc/alchemistry#172]
https://github.com/al132mc/alchemistry/blob/78e7dc9c1342935b99b5fb0694b5fee8c9e0a89b/src/main/java/al132/alchemistry/blocks/combiner/CombinerTile.java#L86-L110

Energy is extracted both during the processing AND at the increment of the output. It should only occur on processing. With default processing ticks of 5 and 100 RF usage for a cobminer, this would imply 500 RF per operation, currently it's 600.

Same issue is in Atomizer, Liquifier, Electrolyzer, Fusion and Fission multiblock code.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
