### ISSUE TITLE
Evaporator crashes game

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [al132mc/alchemistry#173]
Using this on 1.16.5, when I right-click the evaporator without any liquid, everything works fine, but if I put lava in, then right-click, the game crashes. I'd include the log, but it ends without mentioning anything but the last command I typed (`/give @p lava_bucket`). No crash logs were generated either. As long as I make sure to not touch it while there's liquid/items in it, I can just extract with hoppers, though.

Mods are:
chiselsandbits-0.3.4-RELEASE.jar
alchemistry-1.16.5-1.jar
alib-1.16.4-1.jar
appliedenergistics2-8.3.1.jar
architectury-1.12.145-forge.jar
Bookshelf-1.16.5-10.0.7.jar
Botania-1.16.5-416.jar
buildinggadgets-1.16.5-3.8.0.jar
chemlib-1.16.4-1.jar
cofh_core-1.16.4-1.2.1.jar
CommonCapabilities-1.16.5-2.7.0.jar
create-mc1.16.5_v0.3.1c.jar
CTM-MC1.16.1-1.1.2.6.jar
curios-forge-1.16.5-4.0.5.1.jar
CyclopsCore-1.16.5-1.11.7.jar
DarkUtilities-1.16.5-8.0.9.jar
ftb-gui-library-1605.2.1.41-forge.jar
gates-1.7.1.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
jei-1.16.5-7.6.4.87.jar
journeymap-1.16.5-5.7.1.jar
mcjtylib-1.16-5.0.19.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
minecoprocessors-1.16.5-1.0.5-b1.jar
morered-1.16.5-2.1.0.2.jar
Patchouli-1.16.4-51.jar
pneumaticcraft-repressurized-1.16.5-2.12.5-190.jar
ProjectE-1.16.5-PE1.0.1B.jar
Psi+1.16-94.jar
thermal_expansion-1.16.4-1.2.0.jar
thermal_foundation-1.16.4-1.2.0.jar
thermal_locomotion-1.16.4-1.2.0.jar
titanium-1.16.5-3.2.8.4-10.jar
Uppers-0.3.2.jar
[1.16.5]+SecurityCraft+v1.8.21.1.jar
advancedperipherals-0.6r.jar
bperipherals-1.1.2.jar
cc-tweaked-1.16.4-1.96.0.jar
create-mc1.16.5_v0.3.2b.jar
create-stuff-additions1.16.5_v1.0.6.jar
createaddition-1.16.5-20210713a.jar
Cucumber-1.16.4-4.1.10.jar
Disenchanting-forge-1.16.5-1.7.1.jar
elevatorid-1.16.5-1.7.13.jar
entangled-1.3.4-mc1.16.5.jar
flywheel-1.16-0.1.1.jar
IntegratedCrafting-1.16.5-1.0.16.jar
IntegratedDynamics-1.16.5-1.9.0.jar
integratednbt-1.16.4-1.4.2.jar
IntegratedTerminals-1.16.5-1.2.4.jar
IntegratedTunnels-1.16.5-1.8.4.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
kotlin_libraries-1.0-6.jar
Mantle-1.16.5-1.6.103.jar
mightyarchitect-mc1.16.3_v0.5.jar
Mob-Catcher-Mod-1.16.5.jar
MysticalAgradditions-1.16.4-4.1.5.jar
MysticalAgriculture-1.16.4-4.2.0.jar
MysticalCustomization-1.16.4-2.1.5.jar
NaturesAura-34.2.jar
notenoughwands-1.16-3.0.1.jar
OptiFine_1.16.5_HD_U_G8.jar
performant-1.16.2-5-3.66m.jar
PrettyPipes-1.9.4.jar
Resynth-6.2.0-[Minecraft-Forge-1.16.5].jar
simpleplanes-1.16.5-4.4.1.jar
Storage4ComputerCraft-1.16.4-1.2.2.jar
supermartijn642configlib-1.0.8-mc1.16.jar
supermartijn642corelib-1.0.9-mc1.16.5.jar
TConstruct-1.16.5-3.0.4.171.jar
tinyredstone-1.16.5-1.8.3.jar
valkyrielib-1.16.5-3.0.8.0.jar
VendingMachine-1.16.2-1.0.0.5.jar

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
