### ISSUE TITLE
Thorium too hard to obtain

### ISSUE THREAD

**Issue by moon-st0ne** [al132mc/alchemistry#174]
288 Thorium is required to craft all three Fusion Chamber Cores. Currently, the only "vanilla" way to obtain Thorium is via dissolving End Stone and End Stone Bricks, which can give Thorium at a 0.56% chance. That's a 99.44% chance you won't get what you want per End Stone processed. I can't comprehend the math, but if I could, I would find out approximately how much End Stone you would need to process to guarantee you get all 18 ingots of Thorium. 

From experience, I can say it's well into the thousands. I've delivered at least ten full inventories of End Stone over the past two hours and I have...one core crafted.

Please for the love of God, Al, add Thorium to something else. I think Dragon Skulls are a good candidate. They're a rare resource, but not so rare that you are unlikely to find any. Maybe each skull contains 32 Thorium, like how Wither Skeleton Skulls contains 32 Mendelevium?

**Comment by OniyaMCD** [comment]
As someone who does comprehend the math - a 0.56% chance is roughly 1 unit per 178,5 blocks.  For 18 ingots (3 cores) at 16 units each, that's 288 units of Thorium needed.  That comes out to approximately 51500 blocks on average.  (It's a little late for me to get into advanced statistics to get a 95% confidence interval,)

Unless NuclearCraft or a similar mod is introduced for 1.16, this makes fusion one heck of an endgame process.

**Comment by JDLENL** [comment]
I had to manually destroy an entire end island over the course of 3 hours, so that approximation sounds about right. I think I got slightly lucky as I don't believe I delivered over 25000

**Comment by moon-st0ne** [comment]
Stupid Github mobile. Thanks for doing the math, is what I was going to say.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
