### ISSUE TITLE
Nitrate ( NO3)

### ISSUE THREAD

**Issue by Deotexh** [al132mc/alchemistry#175]
Uhm...Hello
Sorry for disturbing I have a problem:
When I try to create Nitrate it only allows me to create Nitrogene Dioxyde (NO2)
Even with JEI + button or locking it don't work (With the + button it do lock but when I unpaused nothing got created, and simply locking will create NO2 instead of NO3)
Sorry for bad english x) x( x) xD XD
Have an excellent day! ^^ ^w^ x) xD XD

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
