### ISSUE TITLE
[1.16] GUI translation 

### ISSUE THREAD

**Issue by Cubichesky** [al132mc/alchemistry#177]
Add the ability to translate the GUI name (ru translation and other)
![изображение](https://user-images.githubusercontent.com/66108320/140633832-08619c90-606c-4a43-bcfe-ccc8bc8316b3.png)
![изображение](https://user-images.githubusercontent.com/66108320/140633869-5da65398-b7f8-40f7-a653-a9094676d6a0.png)
![изображение](https://user-images.githubusercontent.com/66108320/140633871-247fa830-7d38-4118-b854-227a2742f2be.png)
![изображение](https://user-images.githubusercontent.com/66108320/140633874-88d91e34-a705-400b-977f-b5ece601b93f.png)
![изображение](https://user-images.githubusercontent.com/66108320/140633881-80dbd466-fb3e-4a30-afa8-a28c280b589e.png)

**Comment by Dark-Arcana** [comment]
I've been rewriting Alchemistry for 1.18.2. I will not be putting any time into the older versions pre-rewrite as they are the original author's code and I am not familiar with it. However, I do need translations for the new version. Please join the Discord so we can chat about it.
