### ISSUE TITLE
simple addon

### ISSUE THREAD

**Issue by skiller8641** [al132mc/alchemistry#178]
hello, i wanted to make a mod that use element just like yours and a voice in my head said "just make an addon" (also i wasn't knowing how to make a modded crafting table like your combiner) so i wanted to ask a recipe template for the combiner/disolver and other way to use elements so it would be simple to make new recipe.
Thank's.

**Comment by ghost** [comment]
Which Minecraft version did you plan on targeting?

**Comment by skiller8641** [comment]
1.12.2 and maybe beyond (1.16.5 to 1.18.1 and maybe other)

**Comment by skiller8641** [comment]
when i have the template
