### ISSUE TITLE
unable craft

### ISSUE THREAD

**Issue by noc1793** [al132mc/alchemistry#18]
v0.8.1, Chemical Combiner, Cellulose(C6 H10 O5) and Sucrose(C12 H22 O11) recipe identical，Sucrose unable craft。hope to add switch button
![tim 20190223180914](https://user-images.githubusercontent.com/21016380/53285342-4befaa80-379a-11e9-9a77-cc7b556546be.png)
![tim 20190223181001](https://user-images.githubusercontent.com/21016380/53285344-4db96e00-379a-11e9-9822-b2382a5cca64.png)

**Comment by al132mc** [comment]
I've released a new version, v.0.8.2 that should fix this. It changes it so the JEI transfer handler ("+" button) will automatically set the recipe template rather than manually setting it by hand. Recipes should no longer clash like this
