### ISSUE TITLE
[Question/bug(?)] Beryllium Loop

### ISSUE THREAD

**Issue by AlienXtream** [al132mc/alchemistry#180]
its likely im missing something or some other feature is present but looking through JEI the fission chamber requires Beryllium ingots however there appears to be no way to GET Beryllium without said fission chamber. im guessing that it requires a fUsion chamber but the actual specific recipes are not visible?

**Comment by OniyaMCD** [comment]
Check the dissolver results for polished granite, emerald, and prismarine.
