### ISSUE TITLE
beta - Carotene can‘t be combined when using many combiners at same time

### ISSUE THREAD

**Issue by IndefiniteCalculus** [al132mc/alchemistry#181]
I am building a chemical factory using this mod and Create mod. I can't use a combiner to get carotene when I try to start many combiners and dissolvers at the same time.
![image](https://user-images.githubusercontent.com/55014395/158336007-6f87d7a2-121d-460e-b967-905bdbb4fe5b.png)
![image](https://user-images.githubusercontent.com/55014395/158336097-74eaabfa-0c6a-4c98-ba29-7e86b7b7c658.png)

**Comment by IndefiniteCalculus** [comment]
the status of the combiner is the same with other combiners and it's recipe is locked as carotene

**Comment by IndefiniteCalculus** [comment]
I got more details.  When I unlocked the recipe and input C40H56 manually, got C2H2 instead of carotene

**Comment by ghost** [comment]
Could you let me know which version of the mod you were using?

**Comment by IndefiniteCalculus** [comment]
Sorry for taking so long to reply. This is the mod version am using.
![image](https://user-images.githubusercontent.com/55014395/159882524-9a10cab7-57ad-4174-812f-f90c6fa44ebb.png)

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
