### ISSUE TITLE
[1.18.2] Some ores don't have dissolver recipe

### ISSUE THREAD

**Issue by mtbrenner** [al132mc/alchemistry#183]
Alchemistry version 1.18.2-4. Chem lib 1.18.2-2
Testing with Immersive Engineering
Missing Ore recipes:
- Deepslate Coal Ore (Minecraft)
- Deepslate Iron Ore (Minecraft)
- Copper Ore (Minecraft, forge:ores/copper)
- Deepslate Copper Ore (Minecraft)
- Deepslate Gold Ore (Minecraft)
- Deepslate Redstone Ore (Minecraft)
- Deepslate Emerald Ore (Minecraft)
- Deepslate Lapis Ore (Minecraft)
- Deepslate Diamond Ore (Minecraft)
- Bauxite Ore (Immersive E, forge: ores/aluminum)
- Deepslate Bauxite Ore (Immersive E, forge:ores/aluminum)
- Lead Ore (Immersive E, forge:ores/lead)
- Deepslate Lead Ore (Immersive E)
- Silver Ore (Immersive E, forge:ores/silver)
- Deepslate Silver Ore (Immersive E)
- Nickel Ore (Immersive E, forge:ores/nickel)
- Deepslate Nickel Ore (Immersive E)
- Uranium Ore (Immersive E, forge:ores/uranium)
- Deepslate Uranium Ore (Immersive E)
-
(Immersive metal ingots are recognized)

**Comment by ghost** [comment]
Fixed in 1.18.2-5 - All deepslate and regular ores with standard forge tags should work now (as well as any plates/nuggets/blocks/dusts)
