### ISSUE TITLE
1.18.2 Guide book missing entries

### ISSUE THREAD

**Issue by XavierTheSniper** [al132mc/alchemistry#184]
The Alchemistry guide book shows categories but no entries are present

**Comment by border999** [comment]
As a note, I'm finding this in my log and I find it very relevant. It's a message from patchouli
"Error loading book alchemistry:alchemistry_book, using empty contents and ignoring extensions
java.lang.IllegalArgumentException: `category` must be fully qualified (domain:name). Hint: Try `alchemistry:utility_category`"

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
