### ISSUE TITLE
Fails to load world with chemlib 1.18.2-2.0.2

### ISSUE THREAD

**Issue by lucie-sharpe** [al132mc/alchemistry#188]
When creating  a world it displays: "Errors in currently selected datapacks prevented world from loading."
This occurs when using chemlib 1.18.2-2.0.2 there is no issue with earlier versions.

The data inside lates.log is in the pastebin
https://pastebin.com/kUGuyUnQ

**Comment by Dark-Arcana** [comment]
Chemlib 2.0.2 isn't compatible with any existing version of Alchemistry. You will need to wait until the rewrite is done.
