### ISSUE TITLE
tech reborn compatibility

### ISSUE THREAD

**Issue by bigenergy** [al132mc/alchemistry#19]
hello, chemical combine produces items from tech reborn

**Comment by al132mc** [comment]
Is this a problem?

**Comment by bigenergy** [comment]
Yes! Also the mod does not work with IC2
![screenshot_22](https://user-images.githubusercontent.com/17977139/53738559-8c3ce000-3ea0-11e9-9d02-9d1cc7089b56.png)
![screenshot_23](https://user-images.githubusercontent.com/17977139/53738562-9068fd80-3ea0-11e9-9c0f-5d0682a3ccc6.png)

**Comment by bigenergy** [comment]
Are you going to fix this?

**Comment by al132mc** [comment]
To be honest, I don't understand what the bug is.

**Comment by bigenergy** [comment]
items from mod IC2 are not made in a chemical combiner

**Comment by al132mc** [comment]
Perhaps you are just misunderstanding how the mod works? Could you help me understand how your experience is different than mine?

I've recorded a GIF showing how it works for me
[https://imgur.com/nHBt0XO](https://imgur.com/nHBt0XO)
