### ISSUE TITLE
1.18.2 Can't add Recipes via Resourcepack

### ISSUE THREAD

**Issue by JainaProudgurl** [al132mc/alchemistry#190]
Downloaded your mod to add some cool things for a modpack that I'm trying to make. 

Went into the mod itself to get the recipe formatting, then copy and pasted it to a new .json file that I added to data\alchemistry\recipes\dissolver. Then I editted the file for what I wanted to add. Here's the file (I converted it back to txt since github doesn't support .jsons)
[sulfur.txt](https://github.com/SmashingMods/Alchemistry/files/8932855/sulfur.txt)

I'm not sure whats wrong. I even tried moving it to the forge.dusts file just in case, and it still wasn't working. I double checked almost everything, including the resourcepack path to make sure I didn't misspell anything. Everything points to it should be working, but just doesn't.

**Comment by Dark-Arcana** [comment]
Hello. I have been rewriting these mods from the ground up. In the newer as of yet unreleased version of Alchemistry, you should be able to create and load recipes from json in a datapack or by using kubejs. So this issue won't apply anymore.
