### ISSUE TITLE
[1.18.2] Missing Chemical Dissolver Recipes & Recipe Suggestions

### ISSUE THREAD

**Issue by moon-st0ne** [al132mc/alchemistry#191]
guess i'm doing this again, eh?

the following vanilla Minecraft blocks/items are missing recipes for the Chemical Dissolver (some may be intentional):

- Deepslate (and all variants); should probably be similar to stone but with altered rare drops; notably, [slate is composed of quartzite, illite, and chlorite](https://en.wikipedia.org/wiki/Slate)
- Calcite; it's literally calcium carbonate crystals
- Tuff; this is a fun one. tuff is lithified volcanic ash, so it could contain all kinds of interesting elements that normally get spewed out by volcanoes. that sounds like a heady research topic, [so i leave that up to your discretion.](https://en.wikipedia.org/wiki/Tuff)
- Dripstone; according to the block of the week article on minecraft.net, dripstone is the limestone of minecraft. limestone, like calcite, is calcium carbonate, but given it's brown it clearly isn't pure. perhaps iron too.
- Rooted Dirt; same as dirt or grass.
- Hanging Roots; cellulose.
- Raw Ore and their blocks; how you want to balance these is up to you, but i would suggest one ingot per raw ore, keeping the two per ore block; the raw ore blocks then would yield 9 ingots' worth. of course, this is in a vacuum; other mods do it differently and may interfere with this, but i'm just reporting on all the missing stuff.
- Amethyst and its blocks; amethyst is just quartz (silicon dioxide) with added impurities that make it purple. typically, irradiation and iron impurities. maybe you want something more magical than that, since that's just real amethyst. maybe a 1% chance of some radioactive element?
- Netherite and its block; it's a bit odd that ancient debris is fine but netherite has no recipe. clearly, it should yield 64 Au and 64 W per ingot...unless you didn't give it a recipe for balance reasons with ore processing, which is totally reasonable.
- Wet Sponge; sponge has one but wet sponge doesn't.
- Smooth Basalt; should be the same as basalt.
- Crying Obsidian; this one was missed in the 1.16 update; either the same as obsidian or maybe add a chance for something unique.
- Gilded Blackstone; also seems to have been missed. should just be blackstone but with a chance for some gold.
- Moss; cellulose.
- Large/Small Dripleaf; cellulose.
- Spore Blossom; cellulose.
- Glow Lichen; cellulose. and maybe a chance at phosphorus.
- Powder Snow; this is just a thought for 1.19, since forge is adding the fluid api, but powder snow being able to evaporate or atomize into water would be nice, going forward. if possible.
- Glow Berries; cellulose, sucrose, maybe phosphorus.
- Glow Ink Sac; it's an ink sac that glows...but the ink isn't black? it's either cyan or transparent and glowing...i leave it up to you.
- White Dye; titanium white. 
- Brown Dye; probably iron-based, but there are so many iron compounds already...maybe look for a more creative one?
- Melon Slice; no idea how this one is missing. cucurbitacin, sucrose, water.

unrelated, but dragon's breath has 8*Xe added twice. was that an error?

i think that's all of them.

**Comment by moon-st0ne** [comment]
i would suggest adding more of the rare earth elements to some of these unknown formulas like deepslate and tuff, since they're actually quite abundant yet difficult to extract commercially. only 5 REEs are available right now before the reactors.

**Comment by Timbroglio** [comment]
Thanks a bunch for the suggestions! We're working through updating the recipes now and this is a big help.
Definitely planning to add more rare-earth elements to Deepslate, I think that much like with diorite/andesite/etc. it's a good way to harvest some rare elements without Fusion.

**Comment by Timbroglio** [comment]
Added in https://github.com/SmashingMods/Alchemistry/commit/8cd2c076034acc2daeaaf14a8f09101a85d9ed29 and in a bunch of the other commits from before too. Thanks again!
