### ISSUE TITLE
Writing down features so Arcana doesn't forget them

### ISSUE THREAD

**Issue by Timbroglio** [al132mc/alchemistry#192]
- Reactor cores should glow
- Different blockstates for power input
- Connected textures for assembled multiblocks

**Comment by Dark-Arcana** [comment]
Reactor core glowing finished in https://github.com/SmashingMods/Alchemistry/commit/8d430228efcb6042f677a2f61c01ed7a773e38c6

CTM added in https://github.com/SmashingMods/Alchemistry/commit/0ed75cf9a28af98e707237decfd1b366ce9ebeee
