### ISSUE TITLE
minecraft server (1.18.2) crashes with alchemistry while loading 

### ISSUE THREAD

**Issue by Sollos1** [al132mc/alchemistry#194]
here is log https://mclo.gs/5lhqxnK

**Comment by Dark-Arcana** [comment]
You loaded Alchem with the latest Chemlib. They are not compatible. Alchemistry and Chemlib are being rewritten from the ground up. The rewritten Alchemistry hasn't been released yet, so you can't use the latest chemlib. Keep an eye out for releases.
