### ISSUE TITLE
Touch up existing block models

### ISSUE THREAD

**Issue by Dark-Arcana** [al132mc/alchemistry#198]
The existing models don't need to be entirely redesigned. They are iconic to the mod. But we should touch them up to make them more dynamic, handle power states, and have maybe newer textures where appropriate for sections of models (similar to the new reactor casing texture).

**Comment by Dark-Arcana** [comment]
@Timbroglio do we want to make any other changes to the existing block models, or are we satisfied with how they look now?

**Comment by Timbroglio** [comment]
I had meant to do another pass, actually, but I think they're good for the time being.

**Comment by Dark-Arcana** [comment]
Let's leave this open then and schedule a time to do another pass.

**Comment by Timbroglio** [comment]
2023? lol

**Comment by Dark-Arcana** [comment]
I think they're fine enough for now.
