### ISSUE TITLE
Dissolver JEI displays incorrectly

### ISSUE THREAD

**Issue by Timbroglio** [al132mc/alchemistry#199]
JEI lookup for dissolver recipes shows incorrect number/item combinations whenever a recipe has a chance to give nothing (such as Stone), or if the recipe is guaranteed to give multiple items together as a group.

**Comment by Dark-Arcana** [comment]
Thanks for reporting so we can keep a record of it. I've been thinking about this issue and how best to resolve it. I just did a quick and dirty solution when I first wrote it. Long term, I will basically want to "deserialize" the data in a sense. Right now I think I'm just iterating over all of the items in the set. But I should be iterating over the groups instead.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/pull/205
