### ISSUE TITLE
Atomizer can still work without energy

### ISSUE THREAD

**Issue by Pkyd** [al132mc/alchemistry#20]
Forge 14.23.5.2807
Alchemistry0.8.4
alib 1.05
Forgelin 1.7.4

Seem like the Atomizer automatic convert fluid itno element even with or without power. i have test with all machince and only Atomizer have thid bug

**Comment by al132mc** [comment]
Thank you, i'm not sure how this bug slipped through for so long. It has been fixed in development and will be available soon.

**Comment by al132mc** [comment]
I just released v0.8.5 which fixes this issue.
