### ISSUE TITLE
1.18 Elements 72-80 are classified as lanthanides

### ISSUE THREAD

**Issue by Catandcomparator** [al132mc/alchemistry#200]
exactly what the title says. the tooltip of elements 72-80 are all lanthanides when they are transition metals.

**Comment by Timbroglio** [comment]
See I just _knew_ I was gonna do something dumb when making those.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/ChemLib/commit/53a6e1d06586d745a3d3dd0fb18ba674bd46f2aa
