### ISSUE TITLE
1.18 Lanthanides are radioactive

### ISSUE THREAD

**Issue by Catandcomparator** [al132mc/alchemistry#201]
Exactly as the title says, all lanthanides are classified as radioactive on the periodic table, when only promethium is radioactive.

**Comment by Timbroglio** [comment]
Thanks for pointing that out! I was just using a list of the most common radioactive isotopes and wasn't really thinking about the fact that those are mostly pretty stable. Fixed in https://github.com/SmashingMods/ChemLib/commit/317acd9f5f63642ff9f4ce6c9a0cac6c5c25324d
