### ISSUE TITLE
[BUG] Permanent crash on Compactor

### ISSUE THREAD

**Issue by TheRealM18** [al132mc/alchemistry#202]
Hello SmashingMods,

I found a bug, where if you have a compactor, and place cobblestone in it, It will corrupt the world, and will crash your client everytime.
[crash-2022-07-19_11.36.03-server.txt](https://github.com/SmashingMods/Alchemistry/files/9142063/crash-2022-07-19_11.36.03-server.txt)

**Comment by Dark-Arcana** [comment]
Wow that's crazy. I just replicated the crash by putting a single cobblestone in the input slot. I'll get this fixed right away.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/pull/203
