### ISSUE TITLE
1.18.2 wrong recipes combiner

### ISSUE THREAD

**Issue by albertosaurio65** [al132mc/alchemistry#208]
I try to make NH4 by marking the recipe but NH2 always comes out, there is no way to create NH4, whether or not I mark the recipe

**Comment by MasterEnderman** [comment]
https://github.com/SmashingMods/Alchemistry/issues/206

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/pull/211

**Comment by albertosaurio65** [comment]
i cant create NH3, only NH2 or NH3

**Comment by albertosaurio65** [comment]
It doesn't matter what objective he marks, he does whatever he wants, even if i marks co2, if I only put C, C4 is made

**Comment by albertosaurio65** [comment]
that's why I can't make nh3 or co2, because it always makes CO and NH2 (already solved, also NH4)

**Comment by Dark-Arcana** [comment]
You need to press the button to lock the recipe. That prevents it from outputting anything else.

**Comment by albertosaurio65** [comment]
and it is blocked and what is necessary appears in the interface, it still does what it wants

**Comment by albertosaurio65** [comment]
![image](https://user-images.githubusercontent.com/70109413/180621362-4d31b0a0-c8ba-4a3d-b6de-4741b60e9e8b.png)

**Comment by Dark-Arcana** [comment]
Update to the latest version. I fixed this issue already. After updating, you will see a button to lock the recipe. Press that button. Later I will modify the machine to make this make more sense.

**Comment by albertosaurio65** [comment]
I'm sorry, when I went to update it I got distracted with another one and in the end I didn't do it, I thought I had the update
