### ISSUE TITLE
Visual Bug when showing gases in liquifier 

### ISSUE THREAD

**Issue by Crypt1-C** [al132mc/alchemistry#212]
![image](https://user-images.githubusercontent.com/82911966/180385407-0dad0b07-c0cf-4b37-a38b-59c7bbd9a014.png)

**Comment by Dark-Arcana** [comment]
So, I've been showing this bug to a *lot* of devs. They are all stumped. It *should* work exactly as it is. Gizmo from TeamTwilight is of the opinion that the registration process is causing some issue, but not sure how best to fix it. But we are working on this.

**Comment by Dark-Arcana** [comment]
I don't think I can fix this for now. I'll mark it as such.
