### ISSUE TITLE
[Suggestion] add particle effects 

### ISSUE THREAD

**Issue by Crypt1-C** [al132mc/alchemistry#213]
why not add particles inside the reactor once it's fully online and working 
ie . particles will be representing the splitting of atoms in the Fission Reactor

**Comment by Dark-Arcana** [comment]
Hah! This is something I had planned and was going to look into soon (next ish). I have ideas for different particle types, how to spawn them, and what colors to use. Part of making the core glow was the first step to modifying the blockstate around the core.

**Comment by moon-st0ne** [comment]
mekanism fission reactors have a nice cherenkov glow around the fuel rods when the reactor is running, maybe a similar effect around the fission reactor core?

**Comment by Timbroglio** [comment]
That's the plan! A good cherenkov glow for fission, and a plasma aura for fusion. Might need to lighten up the color on the leaded glass a little to make it look good, we'll have to see - I've been kinda torn on "accurate to life" vs "most visually pleasing" when it comes to that glass.

**Comment by Dark-Arcana** [comment]
Particles as it turns out are incredibly complicated if you want them to render translucency. So as not to spend too much time on it, I added a different sort of particle effect. You will see if you download the update.
