### ISSUE TITLE
[Bug]UI lost linkage to JEI

### ISSUE THREAD

**Issue by XieDeWu** [al132mc/alchemistry#216]
Cannot query JEI for raw product placeholders,
Cannot add JEI quick to raw product placeholders,
Now you need to manually query the composition of the precursors.

**Comment by Dark-Arcana** [comment]
I'm sorry. I don't understand what you are saying. Can you please attempt to elaborate?

**Comment by XieDeWu** [comment]
> I'm sorry. I don't understand what you are saying. Can you please attempt to elaborate?

![image](https://user-images.githubusercontent.com/49677093/181500292-9d506d07-7df9-4a50-b416-3bb64ee0b0cb.png)
Sorry,I failed to reply in time recently

**Comment by XieDeWu** [comment]
> I'm sorry. I don't understand what you are saying. Can you please attempt to elaborate?

![image](https://user-images.githubusercontent.com/49677093/181503029-ccba8695-51d8-4627-880b-6038b8cd7e6e.png)
Lack of linkage with JEI.
That's about it.

**Comment by XieDeWu** [comment]
> > I'm sorry. I don't understand what you are saying. Can you please attempt to elaborate?
> 
> ![image](https://user-images.githubusercontent.com/49677093/181500292-9d506d07-7df9-4a50-b416-3bb64ee0b0cb.png) Sorry,I failed to reply in time recently
If you can, right click can also add, the effect will be better

**Comment by XieDeWu** [comment]
> > I'm sorry. I don't understand what you are saying. Can you please attempt to elaborate?
> 
> ![image](https://user-images.githubusercontent.com/49677093/181503029-ccba8695-51d8-4627-880b-6038b8cd7e6e.png) Lack of linkage with JEI. That's about it.

If you can, right click can also add, the effect will be better

**Comment by Dark-Arcana** [comment]
If I am understanding you correctly, your issue is fixed in https://github.com/SmashingMods/Alchemistry/commit/ab8e5bd04c2b12cf912c22411d87ea12006b8b68
