### ISSUE TITLE
Multiblock is not worked in 1.18.x

### ISSUE THREAD

**Issue by korAPUcard** [al132mc/alchemistry#219]
Multiblock of Fusion Chamber and Fission Chamber are not correctly work in MC 1.18.2 version.

Patchouli guidebook is not correctly worked too. Item is exist, but it's broken. Contents are empty.

**Comment by OniyaMCD** [comment]
Please check the comments for issue #207 .  The multiblock structure has been changed.

**Comment by MasterEnderman** [comment]
This is the first version of the complete rewrite of the mod. Everything has been deleted and we started from scratch. The guidebook is still on the list of things that need to be implemented again. Everything else is covered in the issue linked by OniyaMCD.
