### ISSUE TITLE
Suggestion to the mod

### ISSUE THREAD

**Issue by whatsapp2** [al132mc/alchemistry#22]
As a sugestión to the mod:

You should add nitric acid as a chemical. The nitric acid may add recipes to create explosives such as RDX, Dynamite, TNT, Nitrobenzene, Nitrocellulose, etc.

Recipe to create Nitric acid:

1 H2SO4 (sulfuric acid) + 1 KNO3 (Potassium nitrate) = 1 KHSO4 (Potassium bisulfate) + 1 HNO3 (Nitric acid)

Recipe to create explosives:

1 H2SO4 + 1 HNO3 + 1 Glycerin (As an example) = 1 Nitroglycerin + 8 NO2 (Nitrogen Dioxide) + 1 Water 

 

(Well stoichiometry in NO2 isn't exact, but in real life a lot of NO2 is released when nitrating compounds) 

As a "fun" fact my original comment in curse forge got a Spam in less than 5 minutes

**Comment by al132mc** [comment]
I have no idea what's going on with the CurseForge spam filter. Another user complained about the same thing, but I have no control over it unfortunately. I may end up just disabling comments and forward people here.

Anyway, I have no problem with adding sulfuric acid, nitric acid, nitroglycerin, etc, but currently balanced stoichiometric reactions are outside of the scope of what i'm trying to do with the mod (and outside of what it is capable of doing with current machines). I'm still considering what I want to do when I port alchemistry to 1.13 or 1.14...

In a hypothetical "Alchemistry 2" I may move more towards realistic reactions like this and away from cheaty minechem-style reactions, but we'll see. Perhaps i'd port the mod as is AND make a more realistic sequel. If you want to chat about this more feel free to drop by [my discord](https://discord.gg/QVbzp5J)

**Comment by ghost** [comment]
I forgot about this issue, so sorry for the late reply, but i've added this in my project 'Techemistry' which is what became of my ideas above. There is a block called the Reaction Chamber which essentially does what you are suggesting.

[Curseforge](https://www.curseforge.com/minecraft/mc-mods/techemistry)
[Github](https://github.com/al132mc/techemistry)
