### ISSUE TITLE
Missing recipes:  Liquifier machine, dust-to-ingot recipes

### ISSUE THREAD

**Issue by OniyaMCD** [al132mc/alchemistry#223]
Installed the 1.18.2 version of Alchemistry, along with Mekanism (for power) and JEI.  Went into JEI to check what recipes had been changed, for documentation purposes, and clicked on Liquifier.  No recipe was provided.

While looking into the Fusion and Fission reactors, the recipes for the ingots of Tungsten and Yttrium respectively were also unavailable. Going from the element, there is a recipe for the dust shown, using the Compactor, and instinct tells me to smelt the dust, but the only ingot recipes are breaking up a block or crafting from nuggets
![2022-07-26_06 19 28](https://user-images.githubusercontent.com/67665250/180983827-2ca067e2-f9d9-45fb-8e73-96d59bc837d5.png)
![2022-07-26_06 20 34](https://user-images.githubusercontent.com/67665250/180983855-4ad6b5b3-823c-4777-8195-412253c3517c.png)

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/ChemLib/commit/53a6e1d06586d745a3d3dd0fb18ba674bd46f2aa

Will push to curseforge after I get more help figuring out the fluid rendering issue.

**Comment by Dark-Arcana** [comment]
The liquifier isn't used to make ingots. But there are now working recipes for all dusts smelted to ingots in chemlib.

**Comment by OniyaMCD** [comment]
I never said that the liquifier was used to make ingots.  I said that the recipe _for_ the liquifier was missing.

**Comment by Dark-Arcana** [comment]
LOL it is. How did I miss that? Next update.

**Comment by Dark-Arcana** [comment]
Liquifier recipe fixed in https://github.com/SmashingMods/Alchemistry/tree/8e383779b0309884880650e6f9ea4fd32af01725
