### ISSUE TITLE
Fission controller block uses fusion config value

### ISSUE THREAD

**Issue by TechnoVisionDev** [al132mc/alchemistry#226]
Just thought I would let you know that the fission controller block uses the fusion energy config value.

https://github.com/SmashingMods/Alchemistry/blob/2714127a282e0d07fc78d25511048807ec9400b8/src/main/java/com/smashingmods/alchemistry/common/block/fission/FissionControllerBlockEntity.java#L68

**Comment by Dark-Arcana** [comment]
Thanks. Fixed in the commit I'm about to push.
