### ISSUE TITLE
JEI Dissolver recipe doesn't show correctly if there's only a single output

### ISSUE THREAD

**Issue by Timbroglio** [al132mc/alchemistry#227]
As stated in the title - any dissolver with only a single output item shows up, but shows no output.
![image](https://user-images.githubusercontent.com/15707879/182508493-29c140ba-3e7e-4dbe-9e36-e5fc5d502f41.png)

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/ca415438ab9a17b925800bb497538eb40af7d621
