### ISSUE TITLE
Missing dust--->ingot recipes

### ISSUE THREAD

**Issue by TechnoVisionDev** [al132mc/alchemistry#228]
Add smelting recipe for furnace and blast furnace for

- iron dust to iron ingot
- gold dust to gold ingot
- copper dust to copper ingot

I added these to the ChemLib Fabric version but just making the issue here on the Alchemistry repo since ur actively working on it

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/ChemLib/commit/41aa4ee54b49edeeba39ce8db0ccd7f470df723e
