### ISSUE TITLE
Slot Filler get consumed in crafting with Chemical Combiner

### ISSUE THREAD

**Issue by Kenshij** [al132mc/alchemistry#229]
modpack [encrypted ](https://www.curseforge.com/minecraft/modpacks/encrypted_) version R1.3
mod version 1.18.2-5

Slot Filler are consumed in crafting with Chemical Combiner.

Craft Slot Filler, block all slots except first slot of Chemical Combiner. Put 16 Fe in first slot. All Slot Filler are gone.

**Comment by Dark-Arcana** [comment]
All versions of Alchemistry pre-rewrite are no longer supported. Please use the newer versions.

**Comment by OniyaMCD** [comment]
In addition, that's the intended behavior of the Slot Filler.

**Comment by Kenshij** [comment]
> In addition, that's the intended behavior of the Slot Filler.

So you can't use them to block permanently slots in Chemical Combiner. My bad have misunderstood this item.
