### ISSUE TITLE
Chemical Combiner and Dissolver Gui's clashing with player inventory

### ISSUE THREAD

**Issue by Drackion** [al132mc/alchemistry#230]
On the 1.18.2-2.0.5 release of the mod the Gui of the chem combiner and disolver are clashing with the player inventory, with the disolver at least being usable but the combiner is unusable.

![2022-08-09_18 59 54](https://user-images.githubusercontent.com/64641342/183612477-a6ff4544-7e81-4f3c-b534-cf4e927795a9.png)

![2022-08-09_19 13 13](https://user-images.githubusercontent.com/64641342/183612486-012db999-b3c3-415c-b936-76c0ef792873.png)

**Comment by Dark-Arcana** [comment]
What other mods are you using? It's clear that there is some other mod being used to change the color of the screen.

**Comment by Drackion** [comment]
nvm found the issue an file in the modpack Encrypted chaning there texture and causing a clash

**Comment by Dark-Arcana** [comment]
Please make sure to cross post this issue to them so they know to fix it!
