### ISSUE TITLE
Infinite diamonds

### ISSUE THREAD

**Issue by Jin16** [al132mc/alchemistry#232]
Combiner i MC 1.18.2 v2.05  can make Infinite diamonds as seen here
![2022-08-11 21_00_50-Window](https://user-images.githubusercontent.com/20618588/184219413-97393735-c732-4d50-b9a0-b6236135e9e8.png)

**Comment by Dark-Arcana** [comment]
I need more information. Which version of Alchemistry? What is actually happening in your image?

**Comment by Jin16** [comment]
> 
v2.05
the Recipe should look like this ![2022-08-11 21_07_27-Window](https://user-images.githubusercontent.com/20618588/184219844-11512448-2612-4846-95ba-c8d4b7c8934e.png) and it also works, but have found it that if you only put one Graphite in the first slot, and 64 in other, it sill runs

**Comment by Dark-Arcana** [comment]
I can't replicate the issue. The reason I asked about the version is because it's exactly like a bug I fixed a few versions back. Make doubly sure that you are using the latest version of the mod.

https://github.com/SmashingMods/Alchemistry/commit/fb315f97badc755175bf9db194f66f3f594485a2#diff-1bb56895b529469fd5fe3821ffcd1b8baf434ef6cd34bcb434903b99bfce4280

**Comment by Dark-Arcana** [comment]
Ok I tried again but using just 1 graphite in a slot and 64 in another. It's making infinite as you said. I'll look into fixing it asap.

**Comment by Dark-Arcana** [comment]
Should be fixed in https://github.com/SmashingMods/Alchemistry/commit/1d1e4ecdedae23cc693bc235fc4abe12ec8b04ad

**Comment by BideoGemu** [comment]
Hi, can you re-open issue please? I had this bug on the last version of mod.

**Comment by Jin16** [comment]
> Hi, can you re-open issue please? I had this bug on the last version of mod.

I can't seen to reopen it, you have to make a new one, but you can referee to this one

**Comment by Dark-Arcana** [comment]
No, this is fixed. It's just not pushed to curseforge.

**Comment by Jin16** [comment]
> No, this is fixed. It's just not pushed to curseforge.

just out of curiosity, how did it happen again ?
