### ISSUE TITLE
No description/information for graphite.

### ISSUE THREAD

**Issue by Sedus** [al132mc/alchemistry#233]
No description/information for graphite.
1.18.2
2.0.6

![image](https://user-images.githubusercontent.com/76965026/184243241-f4e53ddc-c4f7-47fd-ba64-8d7a702ade84.png)

**Comment by Dark-Arcana** [comment]
Oh hey thanks for pointing this out. We'll get it in the next update.

**Comment by Sedus** [comment]
+calcium_sulfide and calcium_chloride. I just checked the whole json lol

**Comment by Dark-Arcana** [comment]
Yup. @Timbroglio did all of the work on compounds and elements. He added those 3 in the lead up to the full release and missed the descriptions. Super easy to fix.

**Comment by Timbroglio** [comment]
Fixed in https://github.com/SmashingMods/ChemLib/commit/30d4b592550b63503a8ff5e2e87e7704903f9e89
Thanks again!
