### ISSUE TITLE
Incorrect percentage in case of dissolving carrot

### ISSUE THREAD

**Issue by Sedus** [al132mc/alchemistry#234]
1.18.2
2.0.6

I got 2 beta carotene for 64 carrots so 100% is incorrect.

If cellulose+beta carotene=carrot, why dissolve carrots is give only beta-carotene?

![image](https://user-images.githubusercontent.com/76965026/184323824-2878e633-f54c-4df2-a6fb-5967daa2edf4.png)

![image](https://user-images.githubusercontent.com/76965026/184324451-84f9264b-1762-464d-96be-6a33a0dc2728.png)

**Comment by Sedus** [comment]
Same with string UI shows 100% but I got 13 keratin for 64 string.

**Comment by Dark-Arcana** [comment]
Hello. Here is the carrot recipe in the dissolver:

https://github.com/SmashingMods/Alchemistry/blob/1.18.x/src/generated/resources/data/alchemistry/recipes/dissolver/carrot.json

As you can see, it's an absolute (not weighted) recipe with a 20% probability to only give you beta-carotene. As far as I know, this was done on purpose. So the only issue is that the dissolver says 100% when it should say 80% nothing and 20% beta-carotene. I'll look into it.

**Comment by Sedus** [comment]
I don't really understand this but "item": "minecraft:air" is missing from results in carrot.json.
I think somehow the missing 80% is added to beta carotene but only visually.

With minecraft:air added:
![image](https://user-images.githubusercontent.com/76965026/185805534-260b62bf-d073-4229-8d32-f71a62581629.png)

**Comment by Dark-Arcana** [comment]
I'll take a closer look. Thanks for the information.

**Comment by Dark-Arcana** [comment]
This should be fixed in https://github.com/SmashingMods/Alchemistry/commit/d1f82188d1038a79a52475a479578d4609bdcbfc

If you run into any more issues after this is released on CurseForge, let me know, thanks!

**Comment by Sedus** [comment]
Can you check this please? https://github.com/SmashingMods/Alchemistry/blob/1.18.x/src/generated/resources/data/alchemistry/recipes/dissolver/beetroot.json
JEI says 66.67% and 33.33%
@Dark-Arcana
