### ISSUE TITLE
Put 16 water into compactor and it doesn't work

### ISSUE THREAD

**Issue by zinsser901224** [al132mc/alchemistry#235]
game version:1.18.2
mod version:2.0.6
![image](https://user-images.githubusercontent.com/69717616/184441501-864c2bc1-b389-4096-852a-c7bfecb7dc43.png)
Like in the picture, put 16 water on the left side, nothing happened

On the picture, the operation of the machine shows:
1 recipes have been locked
2 pause
3 continue...

What should be set to make machine works?

**Comment by Dark-Arcana** [comment]
This is not a bug. There isn't are recipe to "compact" water. Use the liquifier.
