### ISSUE TITLE
Combiner - using only one type element to craft other complex element

### ISSUE THREAD

**Issue by Sedus** [al132mc/alchemistry#237]
1.18.2 forge
2.0.8a

Not reproducible with 2.0.5

Using only sulfur to craft protein (reproducible because sulfur is part of the recipe):
![image](https://user-images.githubusercontent.com/76965026/185806982-5dec931d-459f-49ab-ac4b-3487196809fb.png)

Not selected recipe (not reproducible):
![image](https://user-images.githubusercontent.com/76965026/185807024-85f357b2-01c6-4293-8f63-6c86da7f3521.png)

Using only hydrogen to craft protein (not reproducible because hydrogen is not part of the recipe):
![image](https://user-images.githubusercontent.com/76965026/185807070-44768383-a55d-4dcd-9536-ef06d204d106.png)

**Comment by Dark-Arcana** [comment]
Thanks for reporting this issue. I made some kind of mistake when changing the combiner to use Ingredients instead of ItemStacks. In my testing, I didn't encounter this issue but it should be easy to replicate. This is a very high priority issue and will be fixed soon.

**Comment by Dark-Arcana** [comment]
Should be fixed in https://github.com/SmashingMods/Alchemistry/commit/2a3987cbe119bd3894f3dafb8cc758c2bc5bcdd6
