### ISSUE TITLE
Adding recipe from JEI will delete items in the Compactor's input slot.

### ISSUE THREAD

**Issue by kalutro** [al132mc/alchemistry#238]
As the title says, if there are any items in the Compactor's input slot when you select a recipe with JEI, those items will be deleted. This is version 2.0.6.

Steps:
 - Place items in Compactor input slot. I used a stack of Silicon Dioxide.
 - Choose recipe from JEI. I chose Andesite.

As you can see in the attached GIF, the stack already in the Compactor is deleted and a single item from my inventory is input.

![javaw_BdJhjTT9RS](https://user-images.githubusercontent.com/69569507/185812516-0278c4ee-b630-46bd-b414-182fea3f2a13.gif)

**Comment by Dark-Arcana** [comment]
Hello. This was fixed in 2.0.8a. I completely rewrote the transfer handlers to prevent them from deleting items. I will ask Cryptic who makes the Encrypted modpack to update soon.
