### ISSUE TITLE
crafting iron 

### ISSUE THREAD

**Issue by RubricGiraffe** [al132mc/alchemistry#239]
not sure if its an issue but i am not able to make iron ingots with the combiner. just want to know how I how to make it with the iron chemical formula thing

**Comment by OniyaMCD** [comment]
There should be a recipe for Iron Dust in the Compactor (used for single-element recipes).  That can then be processed into ingots by smelting.

**Comment by RubricGiraffe** [comment]
im not even able to get any iron the only iron i have is from is from the one quest and when i go onto YouTube to look it up every video has a different hud for the combiner

**Comment by RubricGiraffe** [comment]
if i cant get iron then i cant make the compactor

**Comment by Dark-Arcana** [comment]
Are you playing using a specific modpack?

**Comment by RubricGiraffe** [comment]
im playing on the encrypted modpack

**Comment by Dark-Arcana** [comment]
It's usually up to a modpack maker to make sure that the mod is usable in the context of the pack. However, we can try to help make a better recipe for this to make sure anyone can get access to the compactor without having access to iron.

**Comment by RubricGiraffe** [comment]
I'm even using the 1.18 or whatever the most recent of the mod pack is and like I said I've watched YouTube vids and there combiner hid is like a crafting table format but mine had a "recipe" thing in the middle and then a input I belove it is in the bottom left. Not sure how to put pictures on here so hard to show what I'm dealing with

**Comment by Timbroglio** [comment]
The video you're describing is from the older version of Alchemistry - 1.18+ is a complete rewrite, with a new recipe systems.
If you're playing Encrypted and have no way to make the machine, that's an issue with the modpack, and you should contact Encrypted's developer to report the issue.
