### ISSUE TITLE
Duplication Bug with Diamonds

### ISSUE THREAD

**Issue by SleepyPopp** [al132mc/alchemistry#241]
There's a duplication bug where if you place 20 Graphite in the first slot and a stack in the second slot it would infinitely make diamonds from those chemicals.

![image](https://user-images.githubusercontent.com/81194303/187006976-a5ec7d18-ea7a-4cd7-bddc-46b2b1f77fdf.png)

**Comment by Timbroglio** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/cd587895db88d4ef5ae08b0dbc9771057c94217f
