### ISSUE TITLE
Lock recipe button on the compactor not working. 2.0.9

### ISSUE THREAD

**Issue by krazzykid2006** [al132mc/alchemistry#244]
Alchemistry version 1.18.2 - 2.0.9

The compactor has a lock recipe button in its GUI and it isn't functioning correctly. 
Even when locked, recipes can still be changed by hand, by jei, or by pipes and the player can do nothing about it.

I am trying to take graphite and compact it into coal.
If I do this by hand one stack at a time it is all good. The moment I try to pipe items in, even with the recipe locked, it changes the recipe to try to craft graphite instead of compact it into coal (which it can't craft graphite from graphite so it locks up).

Even with the recipe locked and doing it by hand, if I try to shift click them in too fast it tries to change the recipe to crafting graphite instead of coal.

Also, with the recipe locked, JEI can still change the recipe.

This video should illustrate it all. Sorry I don't have a mic to narrate, but it should be straightforward to follow.
https://www.youtube.com/watch?v=__fRonFNJ5g

**Comment by Dark-Arcana** [comment]
Should be fine now. I think I fixed it a few weeks ago. Please test again with 2.1.3 and report back if it is still broken.
