### ISSUE TITLE
Create Crafts and Addition's Connectors pop off of Reactor Power blocks on opening Worlds 

### ISSUE THREAD

**Issue by ironfprcefeild** [al132mc/alchemistry#247]
Its the title. 

I couldn't recreate it with other blocks that attach like Levers or Paintings. But its really annoying and could effect other mods.

**Comment by Dark-Arcana** [comment]
All pipes pop off. This is to make sure that any pipe that is caching a capability is completely unset to prevent items from being deleted. There is most likely a better solution, but it works for now.
