### ISSUE TITLE
Infinite Diamonds latest version

### ISSUE THREAD

**Issue by BideoGemu** [al132mc/alchemistry#249]
Related to issue #232 , on latest version this bug is still present. It is replicable in the same way.

Do not hesitate if you need additional information, I'm not on my gaming computer, I can't take screen  for now.

**Comment by Dark-Arcana** [comment]
The issue is fixed in my development environment but has not been pushed to a build on CurseForge yet. I've been unable to actually focus on development for a few weeks now due to work obligations. But I promise I'll get it pushed out as soon as I can.

**Comment by BideoGemu** [comment]
No problem, thanks for taking the time to reply.

**Comment by DestinedByte** [comment]
happening to me as well.
issue: Putting graphite into the combiner without selecting a recipe outputs infinite diamonds.
Repeatable: yes
Version: alchemistry-1.18.2-2.0.9

**Comment by Dark-Arcana** [comment]
This was fixed a few versions ago. I forgot to close it. Please make a new issue to track related issues if you find it again!
