### ISSUE TITLE
1.18.2 Incompatibility with TFC on MP

### ISSUE THREAD

**Issue by pehala** [al132mc/alchemistry#258]
# Summary
When running TFC (TerraFirmaCraft) with Alchemistry on multiplayer, I cannot join in with client due to
`io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer minecraft:`
It does happen only on multiplayer, I was not able to reproduce it on singleplayer.
I am not sure if TFC or Alchemistry is causing the error, so I created two identical issues in both projects https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2198

# What happens
The server showed that the client did successfully connect however it seemed it disconnected right after (after the first packet probably).
The client with debug mode shows a little bit more but not much:
[debug (copy).log](https://github.com/SmashingMods/Alchemistry/files/9849486/debug.copy.log)

# Mods
- alchemistry-1.18.2-2.1.2.jar
- chemlib-1.18.2-2.0.11_340666_4035005.jar
- framework-0.2.4-1.18.2_549225_3926054.jar
- Patchouli-1.18.2-71.1_306770_3846086.jar
- TerraFirmaCraft-Forge-1.18.2-2.1.15-beta.jar
- Forge 40.1.80

**Comment by alcatrazEscapee** [comment]
I'll copy my analysis here, as this is a bug in Alchemistry's recipe serialization. TFC is just the unlucky mod that catches it and blows up.

> - Alchemistry recipes have `ItemStack`s with values that are greater than 127 (`Byte.MAX_VALUE`), for instance in [this recipe](https://github.com/SmashingMods/Alchemistry/blob/be9f25cf7ebfcf4351cfe6f52596bac9ecef5ee1/src/generated/resources/data/alchemistry/recipes/dissolver/ores/quartz.json#L23)
> - Alchemistry syncs these item stacks using [`FriendlyByteBuf.writeItemStack()`](https://github.com/SmashingMods/Alchemistry/blob/be9f25cf7ebfcf4351cfe6f52596bac9ecef5ee1/src/main/java/com/smashingmods/alchemistry/common/recipe/dissolver/ProbabilityGroup.java#L59) and [`FriendlyByteBuf.readItem`](https://github.com/SmashingMods/Alchemistry/blob/be9f25cf7ebfcf4351cfe6f52596bac9ecef5ee1/src/main/java/com/smashingmods/alchemistry/common/recipe/dissolver/ProbabilityGroup.java#L68)
> - These methods write the item stack's count as a `byte`
> - When received on client, these item stacks now read a negative count (since writing `128` as a byte turns it into `-128`)
> - The client receives this recipe as producing "-128 air"
> 
> This is a bug in alchemistry. Their recipes are being synced incorrectly, and appear to be empty on client.

Basically, if you have item stacks with a count > 127, you **cannot** use `FriendlyByteBuf.writeItemStack / readItem`. They will write the count as a byte, you will end up with wrong values or empty stacks on client.

**Comment by Dark-Arcana** [comment]
Thanks so much for this very detailed breakdown. This should make it super easy to fix.

**Comment by Dark-Arcana** [comment]
Should be fixed in f378e1c7eb2f603aa46fe58f2cd5312ebb72914b. Now none of the itemstacks in the recipe are larger than 64.
