### ISSUE TITLE
Question: Is it possible to automate the Compactor via RS?

### ISSUE THREAD

**Issue by koalalord9999** [al132mc/alchemistry#259]
Using refined storage (can use AE2 as well, but probably wont).
I was wondering if it were possible to automate several recipes into one compactor, like if I have the crafter on top, feeding in a specific set of chemicals, for this instance, I'd be using Silicon Dioxide to make sand, initially. But for say, if I wanna also craft andesite granite or diorite, would I need a whole new compactor specifically for them, or if my craft says it needs a sand block and puts in 4 SD, then needs a Granite, and puts in 1 SD, would that work?

**Comment by MioAtSwivel** [comment]
I think making more compactor with dedicated recipes isn't an issue. The real problem here is that they don't even work well with vanilla hoppers

**Comment by koalalord9999** [comment]
I don’t k ow how to add any kind of mod support but I would assume being able to add a tag or something to crafters when they craft something would probably be a relatively simple bandaid fix

**Comment by X-Niter** [comment]
Industrial Forgoing Machine that is used to create their addons is a good example here, I think it's best left that the machines adhere to one recipe whenever being automated, and if you want to automate more, you simply make more of the same machine and do a different recipe.
As far as a machine's input and output being potentially "wonky", that's another discussion and surely it's logical that it will get touched up.
Just my two cents is all.

**Comment by Dark-Arcana** [comment]
I honestly agree with that assessment. Whenever I personally have played, I always automate one recipe to one machine. Though I've also watched people like Direwolf with his insane setups having a buffer of a few machines with any given number of recipes. So I know there is some middle happy medium that can be achieved. It's just important to keep in mind that I'm much newer at this and don't have the benefit of 5+ years experience modding like the titans who make those other mods heh.

**Comment by Dark-Arcana** [comment]
Just adding that the sided configuration PR should resolve the wonkiness you experienced with input and output. I'm closing this as I don't intend to pursue your other suggestions, thanks!
