### ISSUE TITLE
Fusion/Fission to simplify making use of all elements.

### ISSUE THREAD

**Issue by BubbaDough** [al132mc/alchemistry#26]
Some elements at present, like Lithium, Zirconium, and Gallium, can be obtained, but have no purpose.  Others, like Strontium and (to an extent) Beryllium can only really be obtained from the item you would want to synthesize them with.  

In addition to adding back features from the now deprecated MineChem, I feel like being able to combine two elements' atomic numbers together, and being able to halve one element's atomic number (rounding one up, and one down to not exclude odd numbers) would ensure that, even if every element doesn't get a Chemical Combiner/Dissolver recipe, no element is a dead end.

Though, I don't know about the giant multiblock structures MineChem utilized for these features, they were quite a pain to put together, and even required another block to put up a hologram of the finished structure for you to fill in.

**Comment by al132mc** [comment]
The Fission and Fusion multiblocks have been introduced in version 0.9.0, which I just released. They are both relatively simple shapes and they don't require any sort of hologram, however I did add Patchouli integration which does give in-world multiblock visualization if a user desires it.
