### ISSUE TITLE
Diamond recipe bug

### ISSUE THREAD

**Issue by szucconi** [al132mc/alchemistry#262]
Using the combiner, it should take two stacks of graphite to make a diamond. In my current version of forge(43.1.30) and alchemistry(2.0.9)/chemlib(2.0.11), I have 16 in one slot and 64 in the second slot and it makes a diamond without consuming the graphite. So it just cranks out endless diamonds, which is a fun mechanic, but cant be intended. Persistences after restarts and moving the combiner, but i didnt try to recreate in another world yet.

**Comment by Timbroglio** [comment]
This was fixed in Alchemistry 2.1
