### ISSUE TITLE
Dissolver creates new item stacks in output without filling up existing stacks

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/alchemistry#266]
https://user-images.githubusercontent.com/24524662/199491909-70a34d5d-6d8a-4ca0-9a00-fe08846f606f.mp4

**Comment by Dark-Arcana** [comment]
I guess I should do some compacting step.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/c0e8c935c06ce7a7ffb01b2b57ceaeee7a25f6dc

Will push to 1.19 later.
