### ISSUE TITLE
Combiner creates items out of thin air

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/alchemistry#267]
Not every recipe works that way and I have no idea what's causing it.

https://user-images.githubusercontent.com/24524662/199492896-223669c6-101e-49d3-89a8-17e20cf8d0a0.mp4

**Comment by bigenergy** [comment]
some problem on 1.18.2

**Comment by bigenergy** [comment]
https://www.youtube.com/watch?v=ZzHiGpeZ7wI

**Comment by Dark-Arcana** [comment]
So this is just with the jei transfer handler right?

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/3380fb2fc9597ee4b6599835152794c2b536c5cc

I will port this forward to 1.19 of course.
