### ISSUE TITLE
Dissolvers take a lot of tick time when doing nothing.

### ISSUE THREAD

**Issue by dualmacops** [al132mc/alchemistry#275]
Version: alchemistry-1.19.2-2.2.1
Pack: ATM8 1.0.2

https://o.tas.sh/#aE60

**Comment by bugescape** [comment]
can confirm this is one of the major lag source of an ATM8 mod @Dark-Arcana @Timbroglio

**Comment by bugescape** [comment]
Please fix ASAP

**Comment by Dark-Arcana** [comment]
I can look into it when I get a chance.

**Comment by Dark-Arcana** [comment]
I haven't had any more reports of issues since the above PR was merged. So I'm going to close this. Please open a new issue with details if you encounter any more serious lag issues. Thanks!
