### ISSUE TITLE
Crash when right clicking any alchemistry machine (Block entity)

### ISSUE THREAD

**Issue by Crypt1-C** [al132mc/alchemistry#279]
1.19.2
43.1.58
Alchemistry 2.2.3
AlchemyLib 1.0.18
ChemLib 2.0.14
Right clicking Combiner Or any Machine (Block Entity) instantly causes the game to crash.

**Comment by Dark-Arcana** [comment]
It requires this:
https://maven.tamaized.com/#/releases/smashingmods/alchemylib/1.19.2-1.0.19

I didn't publish it to CurseForge yet I guess. The last few updates were quick and dirty so that we could get SquirtGun online.

**Comment by Dark-Arcana** [comment]
Try this when it's approved: https://www.curseforge.com/minecraft/mc-mods/alchemylib/files/4132364

**Comment by Pengu-Hunter** [comment]
Latest version of AlchemyLib fixed issue for me, thanks for the quick fix.
