### ISSUE TITLE
combiner closes when typing inventory key in search bar

### ISSUE THREAD

**Issue by kn1g0** [al132mc/alchemistry#280]
basically the title when you type your inventory open/close key (in my case I, not sure if that changes anything) it closes the inventory

**Comment by X-Niter** [comment]
@kn1g0 , What version?

**Comment by NorthLake** [comment]
> @kn1g0 , What version?

Happens to me as well if I use a custom keybind. If I set the inventory keybind to e the issue doesn't occur.
Playing Encrypted 2.1.3, which has Alchemistry 2.0.9 (1.18.2)

**Comment by Dark-Arcana** [comment]
I don't account for custom keybindings and I don't really plan to do so right now.
