### ISSUE TITLE
Input slots

### ISSUE THREAD

**Issue by harryijim** [al132mc/alchemistry#283]
The dissolver does not seem to have a fixed input slot when inputting directly into it. Tested with other pipes such as PipezMod, AE2 and RS. When inputting items into the dissolver the processing input as well as the output slots are filled with the items being inputted.

**Comment by Dark-Arcana** [comment]
Which version of the game and mod? Do you have any images you can share?

**Comment by Azruine** [comment]
![2022-12-22_17 27 11](https://user-images.githubusercontent.com/6277538/209091195-8b7ed0b4-7e6f-4a06-907c-2d828efb634c.png)
![2022-12-22_17 27 53](https://user-images.githubusercontent.com/6277538/209091216-9e74a792-7ddf-4ff0-9a16-ffdc21c6cb70.png)

Graphite goes output slot :(

Alchemistry 1.19.2-2.2.3
ATM8 1.0.6b

**Comment by Dark-Arcana** [comment]
Ok thanks for reporting this. I don't know why that's happening as of now. The output should be invalid for any item to be inserted. So I'll have to look into it when I get a chance.

**Comment by Dark-Arcana** [comment]
This should now be resolved with the sided configuration PR.
