### ISSUE TITLE
jei doesn't show any recipes for the elements

### ISSUE THREAD

**Issue by JannikBulow** [al132mc/alchemistry#286]

**Comment by Timbroglio** [comment]
Please include mod version, minecraft version, and modpack version (if applicable)

**Comment by JannikBulow** [comment]
> Please include mod version, minecraft version, and modpack version (if applicable)

1.0.35, 1.12.2, own modpack. in the order you said

**Comment by PyroBurnem** [comment]
can confirm this on mc 1.18.2, forge 40.2.0, jei 10.2.1.1002, alchemistry 2.2.1, chemlib 2.0.16 and alchemylib 1.0.20 on a fresh install (which is basically latest of everything as of time of writing).

as seen below however,
![image](https://user-images.githubusercontent.com/31893867/215507590-43c76e89-3897-424d-99eb-e6d4da54d66c.png)
![image](https://user-images.githubusercontent.com/31893867/215507642-29e2787c-3c05-4035-8ad3-3f3b701abf30.png)
![image](https://user-images.githubusercontent.com/31893867/215507701-2cd7b566-8e61-47cf-b16e-8f180bad346f.png)
![image](https://user-images.githubusercontent.com/31893867/215507758-fef1f3f1-0bd7-4cc4-a22d-7ee4d0118acd.png)
![image](https://user-images.githubusercontent.com/31893867/215507808-93b2fe4b-de32-4345-96b9-f1fe21d27d15.png)
it appears for me only the atomizer and liquifier has issues, so i cannot attest to the validity of 'any' recpies.

**Comment by Gogo08190** [comment]
Same problem on 1.18.2
![image](https://github.com/SmashingMods/Alchemistry/assets/41335079/8d618ec1-449d-4349-bbad-8832792edde3)

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/eb812f503daf7d1c617b66059a316f32e5b95fbd for all Minecraft versions using JEI 10.
