### ISSUE TITLE
Pulling items out of a Dissolver doesn't just pull out the outputs

### ISSUE THREAD

**Issue by nok-ko** [al132mc/alchemistry#288]
There seems to be an issue in the Dissolver's inventory implementation. When using Mekanism's Logistical Transporters to pipe items in and out of the Dissolver, the pipes take the items in the input slot as well as those in the output slot.

This is annoying. Using only Mekanism, I can work around this issue by using Logistical Transporters (Mekanism's version of filtered/sorting pipes) instead of pipes when pulling out of a Dissolver, but I don't think it's supposed to happen at all.

Another similar inventory issue was reported [here](https://github.com/SmashingMods/ChemLib/issues/42), but on the wrong Issues page.

**Comment by Prayexel** [comment]
Adding to this problem; If you use an "Item Pipe", from the Pipez mod, to load cobblestone into the Dissolver automaticly, the cobble first gets into the correct input slot. However once that Input slot is full, more Cobblestone gets added into the Output slots of the Dissolver.

**Comment by X-Niter** [comment]
@Prayexel 
https://github.com/SmashingMods/Alchemistry/issues/283

**Comment by DJMo13** [comment]
The problem exists with refined storage as well, I guess the systems are all thinking that the dissolver has 13 inventory slots and not one input and twelve output slots; the 1.18 version works just fine...

**Comment by Dark-Arcana** [comment]
This should be resolved for 1.18+ with the sided config PRs.
