### ISSUE TITLE
Fusion Multiblock not working (AllTheMods8)

### ISSUE THREAD

**Issue by Prayexel** [al132mc/alchemistry#289]
Sooo Im playing the All the Mods 8 Modpack (v 1.0.7) and i just build the Fusion Multiblock. Or better said, I tryed to build it. But no mather what i do, it simply doesnt complete into the multiblock it should be. Its still all its own blocks and I get no usable interface.

Okay so i fixed my problem; The problem i had was that in the 3d view of the Multiblockstructure one Block at the bottom missing is (or better said its meant to be air/empty). However, something I dont remember mentioned anywhere is, that in order for the Multiblock to be valid and become that structure, you need to place the "Fusion Chamber Controller" last. According to my experience with other mods this shouldnt be a requirement at all for Multiblockstructures, but even if it is, it should be stated so in the Book.

**Comment by Dark-Arcana** [comment]
It's not required to be placed last. It's designed to update if you place the controller first. Never seen it as an issue before. Might be some kind of mod interaction I don't know about present in ATM8. Would be interested in more information if possible.

**Comment by Prayexel** [comment]
Well anything I can provide to you. So I tried buildign the Multiblock like in the book (visualized in 3d) in Multiplayer and Singleplayer. 
Here are the first problems comming: You need to place a reactor casing underneath the fusionrod which the 3d visualization from the book shows as wrong placed (indicated by the red cube). However theres one additional thing "wrong" with the 3d visualization. If you want to place the Fusion Chamber Controller down from the outside of the reactor, it doesnt recognice the block as placed (indicated by the progressbar and numbers which dont increase (for example 98 blocks placed, place the chamber, its still 98). However placing the Fusion Chamber Controller from the "inside" of the reactor does count as correct.

And as I already figured out, if you place the Fusion Chamber Controller not as last block, the structere counts as complete in the Book visualization, but you get no usable interface as its not completet.

**Comment by Prayexel** [comment]
![2023-01-03_01 30 43](https://user-images.githubusercontent.com/31209483/210287267-93697a7c-d71e-4d90-b638-64df336d4871.png)

Everything is placed (even the needed block underneath the fusion cores) except the "Fusion Chamber Controler" and the one Reactor Glass above it

**Comment by Prayexel** [comment]
![2023-01-03_01 30 56](https://user-images.githubusercontent.com/31209483/210287351-422f2517-a09e-4736-a283-e7243422f21f.png)

Placing the Fusion Chamber Controller from the outside. Still 98/100 blocks of the structure placed, so the Fusion Chmaber Controller did not get recognised.

**Comment by Prayexel** [comment]
![2023-01-03_01 34 50](https://user-images.githubusercontent.com/31209483/210287403-e09eb0b3-ea47-43d3-89cd-c38c2c07a1e1.png)


If the Fusion Chamber Controller is instead Placed from the inside, it counts towards the Blocks (99/100)

**Comment by Prayexel** [comment]
![2023-01-03_01 31 13](https://user-images.githubusercontent.com/31209483/210287441-c4fa772c-687e-4eaf-a5ad-8492a1ad0ce6.png)

Placing the Fusion Chamber Controller last, even if it gets not recognised as placed by the visual fixes the problem; and the Multiblockstructure can be used as inteded

**Comment by Prayexel** [comment]
![2023-01-03_01 39 49](https://user-images.githubusercontent.com/31209483/210287499-a3e29fb1-f8bc-437b-8332-6dbef085f55d.png)

In this screenshot I placed the Fusion Chamber Controller as pre-last block (so block 99) and the glass as last block (100) and the Structure is said to be incomplete as i would need to remove the "false" reactor casing underneath the Fusion Cores. The structure isnt complete that way and is not usable.

**Comment by Prayexel** [comment]
However, what I have to add is; those bugs dont seem to appear consistantly. Sometimes when i try to build the structure, these bugs as described above do happen, but sometimes it works as intended. Sadly I´m not sure what causes this bug to appear sometimes but not all the times

**Comment by Dark-Arcana** [comment]
This isn't a bug. Patchouli is the mod that adds the book and the multiblock structure. It doesn't know which direction the block needs to be facing, or at least it's wrong for some reason. So it's not counting toward completion in patchouli because it thinks that you need to place it inward. Ignore what the book says and just use it as a general guide.

The fusion block does not need to be placed last. But it does need to be placed such that the screen faces you.

**Comment by Prayexel** [comment]
Interesting what you say.

Ok so yeah ignore the book, got that, np.

However you just wrote that the Fusion Chamber Controller needs to be placed with the screen towards me, and I can tell you, that was certanly not the case when i completet it. Simply placing it last worked, or in some cases placing it, facing any directon and completing the multiblock structure. So it seems that the screen facing me isnt a real condition, or at least it seems to be ignored.

And yes I get you, the fusionblock doesnt need to be placed last. But from my experience, if I dont place it last, i have a 50/50 chance of getting a working fusionmultiblock or not. Having no interface or having one.

**Comment by Dark-Arcana** [comment]
> So it seems that the screen facing me isnt a real condition, or at least it seems to be ignored.

This isn't possible. The multi-block validator is based on the position of blocks relative to the controller. So if you place it facing the opposite direction, it won't validate because it doesn't have all of the blocks in the right position.
