### ISSUE TITLE
Fission reactor needs instructions

### ISSUE THREAD

**Issue by flutistno3** [al132mc/alchemistry#290]
I am using this mod through curseforge in a mod pack I created. I also have mekanism. I understand how to BUILD the fission reactor using the guidebook, but not how to power and use it. How do you give it RF? Connecting mekanism power cables doesn't seem to work. I can open the gui, but when I put, for example, uranium in it, nothing happens. I assume this is because it isn't powered. You could add a page to the guidebook that explains how to operate the reactor(s). It also refers to a block as the "energy input" that does not exist. It has "energy" blocks and "input" blocks, but I've tried powering both to no avail.

**Comment by Founntain** [comment]
To power your Fission Reactor you need to supply it with FE through the Reactor Energy Block. Just put any cable, that transfers FE and it should work fine. If it doesn't connect, your reactor has some errors in the building and you need to fix them first.

**Comment by flutistno3** [comment]
I figured out my problem. You must use a configurator to get the cable to connect.  I just think the directions could be better in the manual. Not saying you need to change it. I'm just dumb. Lol

Sent via the Samsung Galaxy A13 5G,an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
