### ISSUE TITLE
Combiner diamond dupe 

### ISSUE THREAD

**Issue by AlvaroMartinezSilva** [al132mc/alchemistry#292]
Hellow i discovered that if u fill the first slot with less than 64 garphite and the second with 64 it starts generating infinite diamonds

https://user-images.githubusercontent.com/60732646/214838964-417a6bd2-ed50-4b4a-acad-26b7111f7f0d.mp4

**Comment by Dark-Arcana** [comment]
This bug was resolved many months ago. The modpack you are playing did not update the mod to the version that fixed it.
