### ISSUE TITLE
Why cant I use a hopper with the dissolver?

### ISSUE THREAD

**Issue by Multi-ManStudio** [al132mc/alchemistry#293]
For SOME reason, whenever I try to have a hopper input items into the  dissolved, it places items into the input. Which it should! But after the input is full, it starts filling the output as well. Which is a tad obnoxious. Is there any way to fix this? I'm trying to automate Yttrium, but it's an ABSOLUTE pain.

**Comment by Dark-Arcana** [comment]
None of the Alchemistry machine blocks have sidedness taken into consideration. It was a feature I wanted to implement and hadn't been able to get to yet. Hopefully work and other stuff catches up soon and I can work on this again.

**Comment by F8enjoyer** [comment]
Rather than using block sidedness, could it be possible to make all insertions go to input slots, and all extractions come from output slots, regardless of which side they come from?

This would give much more flexibility when paired with pipes, AE2, or other mods.

**Comment by Dark-Arcana** [comment]
That could work. Right now I'm using a combined inventory wrapper. Thing is though I don't have time or the motivation to work on this right now, mostly due to work being a higher priority for my mental bandwidth. But perhaps that's a quick and workable solution.

**Comment by Dark-Arcana** [comment]
Everything should be working as you expect it now with the new sidedness feature implemented a few weeks ago.
