### ISSUE TITLE
Fusion reactor not working all the mods 8

### ISSUE THREAD

**Issue by Jgordan775** [al132mc/alchemistry#294]
![image](https://user-images.githubusercontent.com/124013135/215643553-1ba3ae44-2859-4cef-be42-493a73855a0a.jpg)
I have built the fusion chamber using the guidebook, but I am unable to open the menu from the fusion chamber controller even when the reactor has power. I am playing using all the mods 8.

**Comment by Timbroglio** [comment]
Can't see the top in that pic, is it a solid 5x5 of plating on top as well?

**Comment by Jgordan775** [comment]
> Can't see the top in that pic, is it a solid 5x5 of plating on top as well?

Yes, and it gave me the notification for completing the build when I filled in the reactor with the quest book guide

**Comment by Timbroglio** [comment]
Break and replace the controller

**Comment by Jgordan775** [comment]
> Break and replace the controller

I have tried this as well to no avail

**Comment by Founntain** [comment]
Do you have a free block below the Fusion coils ( the yellow thing in the middle )
If YES, place a block below it even when the schematic says otherwise. IT NEEDS a block below it to work.

**Comment by Jgordan775** [comment]
> Do you have a free block below the Fusion coils ( the yellow thing in the middle )
> 
> If YES, place a block below it even when the schematic says otherwise. IT NEEDS a block below it to work.

Thank you this fixed it

**Comment by Dark-Arcana** [comment]
Yeah I wish I knew why the schematic doesn't appear correctly. Might be a bug in Patchouli or a mistake on my end. If anyone has input let me know and I will fix it when I get a chance.
