### ISSUE TITLE
Buckets of chemicals not working

### ISSUE THREAD

**Issue by Jgordan775** [al132mc/alchemistry#295]
When using the buckets of hydrochloric acid as well as the bucket of epinephrine they are not giving the effects they describe.![image](https://user-images.githubusercontent.com/124013135/215918652-15235078-5af7-4607-831d-94da64175faf.jpeg)![image](https://user-images.githubusercontent.com/124013135/215918668-0bdc1aa8-725a-44b3-8e35-cb9dcc417d75.jpeg)![image](https://user-images.githubusercontent.com/124013135/215918673-d2145477-76d6-4376-a3c0-b66536c5f9b1.jpeg)![image](https://user-images.githubusercontent.com/124013135/215918681-ea610536-0fa1-4fe0-b591-2b910e0a2043.jpeg)!

**Comment by Dark-Arcana** [comment]
What version of Chemlib?

**Comment by Jgordan775** [comment]
> What version of Chemlib?

Minecraft 1.19.2 version 2-2.0.16

**Comment by Dark-Arcana** [comment]
I can't replicate this issue in the latest version. Can you try?
