### ISSUE TITLE
Combiner Lock recipe bug

### ISSUE THREAD

**Issue by Slickl** [al132mc/alchemistry#296]
Im currently playing the latest version of atm7 to the sky and when i lock the recipe the block wont pull anymore resources if hes got one of the resources. theres no way to do thos properly without integrated dynamics and getting the raw values and yea.. cant automate like this, was this fixed in a later version? i can't belive no one found this before.

Example:

Slime balls, as soon as only either 1 sucarose or protein is in the combiner he wont pull anymore. I tried fixing this manual with mekanism filters, pipez filter an so on.

**Comment by Slickl** [comment]
My current solution is to use the mekansim filter and force him to never send less or more than 2, but that aint efficent

**Comment by AnasterianSunstrider** [comment]
I have the same problem. The combiner won't accept items anymore once the recipe is locked and when i unlock the recipe it just gets obsessed with another recipe and won't let me change it back to what it was before. Please fix this as soon as possible.

I'm using 1.18.2

https://user-images.githubusercontent.com/26551993/226103882-b1fdb454-a390-460c-97b8-3da1997f7546.mp4

**Comment by Dark-Arcana** [comment]
This should be resolved. Re-open if you can replicate with the latest version of the mods.
