### ISSUE TITLE
Make the machine blocks recipe catalysts for JEI

### ISSUE THREAD

**Issue by aaronhowser1** [al132mc/alchemistry#297]
(Screenshots use REI but same thing applies)

![image](https://user-images.githubusercontent.com/15698722/217602454-2daa7fd7-076b-4071-ba62-0cb942927cba.png)
![image](https://user-images.githubusercontent.com/15698722/217602607-fd482b52-f62d-4e47-a66c-ec712b9d89d0.png)

Normally, hitting U on Furnaces or Chemical Injection Chambers or whatever other machines from mods shows all the recipes that use that machine. Alchemistry doesn't do that though, so it just looks like the machines don't do anything.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/0f354d459f9aa04b5bae452ebcc60772caa4d71c for all Minecraft versions of the mod.
