### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Makxspa** [al132mc/alchemistry#299]
Hi, the modification is only in English. I know Polish and here's my question: Can I add a translation to the modification? I know there is such a possibility. Thank you in advance.

**Comment by Dark-Arcana** [comment]
Hello! There is already a Polish translation in the mod:

https://github.com/SmashingMods/Alchemistry/blob/1.20.1/src/main/resources/assets/alchemistry/lang/pl_pl.json

You might be using a different version that doesn't have this. If it's an older version that is no longer maintained, then you will have to load a custom resource pack with the translations.
