### ISSUE TITLE
Crash when breaking enderio conduit attached to evaporator

### ISSUE THREAD

**Issue by ESTPlayer** [al132mc/alchemistry#3]
The following crash happens when trying to remove conduit attached to evaporator.

Step 1: Place evaportator
Step 2: Place item/fluid conduit on top of it
Step 3: just in case relog/unload chuncks
Step 4: Try breaking the conduit(bundle)
Step 5. Crash

https://paste.dimdev.org/ejaqezukil.txt - crash log

Mod list and everything neccessary is also there.

**Comment by al132mc** [comment]
I am going to close this issue. If anyone believes this is still a problem they are welcome to open a new issue
