### ISSUE TITLE
Certain recipies are improperly implemented.

### ISSUE THREAD

**Issue by davidthehat** [al132mc/alchemistry#30]
I was trying to create tungsten from white antimatter and was having some issue.  It turns out that there is one recipe for two antimatter creating 5 SiO2, and another for one antimatter having a small chance for tungsten and a larger chance for SiO2.  This holds true for the other antimatters.  I believe this may be a crafttweaker issue rather than a mod one, but I though to post here anyway.

**Comment by al132mc** [comment]
This has been fixed in v0.4.14 which I uploaded an hour or 2 ago, though i’m unsure if it has been synced to the twitch launcher yet
