### ISSUE TITLE
[Suggestion] More control over input/output slots when using pipes

### ISSUE THREAD

**Issue by callumok2004** [al132mc/alchemistry#303]
One issue that really upsets us when attempting to automate a Dissolver is when using a pipe to import items, the items will go into the output section if the input is full, and a pipe pulling from the output also pulls from the input - there is no directionality per se, it would be really nice to have more control over this!

**Comment by Quest79** [comment]
I think this is less a suggestion and more asking them to make this work how it should. This is a huge problem. We have been piping and automating for a decade, kind of a huge oversight.

**Comment by Dark-Arcana** [comment]
A feature was added a few weeks back to allow selecting the input/output of a given side of the machine to make automation easier. I hope that helps, thanks to geolykt for the help.

Though I will point out that the hand wave "we have been piping and automating for a decade, kind of a huge oversight" isn't helpful.
