### ISSUE TITLE
Several glitches with the fusion reactor in 1.18.2

### ISSUE THREAD

**Issue by AnasterianSunstrider** [al132mc/alchemistry#306]
When I first built the fusion reactor the textures were switching between being connected and non-connected. Altough entering my world again seems to have fixed this particular issue a new one has emerged. It seems like everytime I enter my wolrd the wire connector from Immersive Engineering that I attached to the reactor energy block breaks, and the pipe from Pipez that I attached to the output gets disconnected. I would also like to mention that when I first built the reactor using the blueprint from the Alchemistry catalogue it showed that I was missing the 100th block in the form of some tiny red cube at the place of one of the reactor casings even though the reactor was already functional.

**Comment by Camildabeast** [comment]
I also see the red cube in place of a reactor block and adding the controller block doesn't seem to register so it stays at 99/100. Then the "screen" just flashes red and it won't power up. The crazy part is that it was working an hour ago and it seems to have spontaneously stopped functioning.

**Comment by jlwinter99** [comment]
I'm having the same issue. It's making the fusion reactor completely useless.

**Comment by Geolykt** [comment]
Your issues are addressed by #309 and #310 for 1.19.2; I will backport the PRs to 1.18.2 should the interest arise

**Comment by Dark-Arcana** [comment]
I backported to 1.18.2 the other day.
