### ISSUE TITLE
Crash when using any machine from Alchemistry

### ISSUE THREAD

**Issue by DizzyDJW** [al132mc/alchemistry#312]
AlchemyLib Ver: 1.19.2-1.0.20
Alchemistry Ver: 1.19.2-2.2.4

Modpack: ATM8

Crash Report: https://mclo.gs/fyrPG4k

Constant issues with this mod conflicting with literally every single mod in the modpack in some way or another. Can't use Ars blocks nearby without a crash, can't open Refined Storage system with Alchemistry blocks nearby without crash, can't open Sophisticated Backpack with Alchemistry blocks nearby without crash

**Comment by Geolykt** [comment]
Hello! This issue has already been fixed in dev (via https://github.com/SmashingMods/AlchemyLib/pull/4) and the fix will be published once the needed tests have been finished.

**Comment by Dark-Arcana** [comment]
Oh thanks Geo! I was looking for this exact fix to point out here. As for the OP, I will be releasing an update and ATM will pick it up soon.
