### ISSUE TITLE
Combiner locking not working

### ISSUE THREAD

**Issue by warderbrad** [al132mc/alchemistry#313]
I am using version alchemistry-1.18.2-2.0.9.jar. I have a combiner and select a recipe. I press the lock button. The button changes to say unlock but the slots still allow for anything to be placed in any slot. This makes automation impossible as slots get overfilled and it stops processing. 

In case this is a mod interaction or something else. I am playing the Encrypted_ pack. 

If anyone has more questions I am happy to give more detail. I am just not sure what more to tell.

**Comment by Dark-Arcana** [comment]
Encrypted is using a really old version of Alchemistry. This was fixed quite some time ago, but unless the modpack updates the version of Alchemistry it uses, you won't get the fixes to play with. You can manually update the mod version in your local instance. I've also already asked Cryptic to update it a few times lol.
