### ISSUE TITLE
Combiner Crashing in All The Mods 9

### ISSUE THREAD

**Issue by SkyeFell** [al132mc/alchemistry#319]
Hello!
I hope to not be bothering considering che Combiner seems to be raising quite a few issues recently (1.20.1)

I'm playing on the **1.20.1 modpack All The Mods 9 vr. 0.0.39** in a private server where we're having **major trouble with the Combiner**
Every time I try to put materials into the machine, try to take them out, or sometimes even _interact with the block_ it crashes giving a plethora of errors. I'm not sure if they match with the other ones reported on here, but I guess I might just give it a try at this point. I've crashed over 15 times, as I really, really, really want it to work but it just won't. If you need a copy of the world or more information (or whatever else) feel free to ask! I hope this gets resolved.
Have a great day and thank you in advance!

Here's a crash report
[crash-2023-07-17_18.55.43-client.txt](https://github.com/SmashingMods/Alchemistry/files/12072001/crash-2023-07-17_18.55.43-client.txt)

**Comment by Sudoasroot** [comment]
this is the same error as #316

**Comment by SkyeFell** [comment]
I see, thank you, I really couldn't tell. 
If I can be of further assistance do tell.

**Comment by Dark-Arcana** [comment]
This is confirmed to be fixed.
