### ISSUE TITLE
Persistence Across Loads

### ISSUE THREAD

**Issue by jelaw21** [al132mc/alchemistry#32]
If I leave a bunch of silicon dioxide in Dissolver and log out. When I log back in I have to replace the silicon dioxide in order for the machine to start running again.

**Comment by al132mc** [comment]
Could you give me more information specifically on how I can duplicate this?

**Comment by al132mc** [comment]
We've since chatted on discord and it was actually the Combiner causing this issue, not the Dissolver. This has been fixed in 1.0.9
