### ISSUE TITLE
Walter white fav thingies production

### ISSUE THREAD

**Issue by beliboba** [al132mc/alchemistry#324]
Is it possible to create blue candies from breaking bad with this mod??? Any tips?

**Comment by Dark-Arcana** [comment]
No. This should not have been added as an issue. Illicit substances are against the Minecraft EULA and will not be added back into this mod.

**Comment by beliboba** [comment]
What about create:broken bad?

**Comment by beliboba** [comment]
Just asking

**Comment by Timbroglio** [comment]
Hi! No means no. Go away.
