### ISSUE TITLE
[Suggestion] Add a few new salt-based recipes 

### ISSUE THREAD

**Issue by cybercat5555** [al132mc/alchemistry#33]
Title. Items with the following OreDict definitions should decompose into/be combined from one Sodium and one Chlorine
 ```
lumpSalt
materialSalt
salt
itemSalt
dustSalt
foodSalt
```
Also for mod compat, the following should be able to decompose into/be combined from 1-2 Potassium Nitrate(s)
```
dustSaltpeter
nitrate
nitre
```

**Comment by al132mc** [comment]
This was added in v1.0.3, though with higher quantities. Please re-open this issue if you have any concerns about the implementation
