### ISSUE TITLE
ATM8 Alchemistry Fusion (& Fission) Reactor Controller not working. 

### ISSUE THREAD

**Issue by SahriCahri** [al132mc/alchemistry#330]
![2023-10-05_18 12 00](https://github.com/SmashingMods/Alchemistry/assets/58496152/66df9fb1-8134-4bc6-8470-7304feb4b530)
![2023-10-05_18 12 01](https://github.com/SmashingMods/Alchemistry/assets/58496152/5562de88-23a1-4c2d-be32-fc37775da6c2)
It's receiving power, and the items I'm piping in. I'm unable to interact with the UI though.

**Comment by Dark-Arcana** [comment]
When the screen is in that state, it means you have built it incorrectly. Fusion controller needs Fusion core, same with Fission controller needing Fission core. You need one item input block, one item output block, and one energy input block to be placed anywhere in the outer edge of the multiblock structure (so not where glass is at, only edges). I don't see those blocks so I can only conclude you have built it wrong.

**Comment by SahriCahri** [comment]
I see.
