### ISSUE TITLE
[Question]Where I should put the file?

### ISSUE THREAD

**Issue by Pippo777** [al132mc/alchemistry#331]
I put the file in the config, and changed some value of the mod, but it doesn't change anything in the game.

**Comment by RemagOfficial** [comment]
what file? how did you put "the file" in the config? how did you change a value in the mod?

**Comment by Pippo777** [comment]
I downloaded the Alchemistry file and put that in the config, and I opened C:\Users\...\AppData\Roaming\.minecraft\config\Alchemistry-1.19.x\src\generated\resources\data\alchemistry\recipes\dissolver, so I changed some value in the recipe of the chemical compounds but I guess this doesn't works like that.

**Comment by RemagOfficial** [comment]
you dont put mods in the config folder, you put them in the mods folder

**Comment by Geolykt** [comment]
Nope. What they want to create is a datapack.
Given the frequency of this question we really ought to think about whether it makes sense to document this properly or make it even easier to create new recipes

**Comment by Pippo777** [comment]
I resolved in the end, thank you guys

**Comment by Dark-Arcana** [comment]
> Nope. What they want to create is a datapack. Given the frequency of this question we really ought to think about whether it makes sense to document this properly or make it even easier to create new recipes

This is a good point. Perhaps I can talk to the Akliz team about making a help doc for our knowledgebase about how to make a datapack. We can use Alchemistry as an example. And then we can put a link here or even just copy the text into the github wiki pages.

**Comment by Dark-Arcana** [comment]
I'm going to close the issue, but I assigned it as a reminder for myself.
