### ISSUE TITLE
ATM9 Fission Chamber Not Working

### ISSUE THREAD

**Issue by CoolerProYT** [al132mc/alchemistry#337]
![image](https://github.com/SmashingMods/Alchemistry/assets/118531227/505cd94d-3e45-4c1b-8904-8e8b0a307481)

I followed the book to build this chamber, after finish build i connected it to power cable, output to chest, and input connect to the controller, the item also passed into controller, but the machine is not working, also no gui showing.

**Comment by Geolykt** [comment]
Is there any info why this issue was closed? It may benefit other people who stumble on a similar problem

**Comment by Dark-Arcana** [comment]
I think the issue is that they were trying to use the controller to input items while they needed to use the item input block below.

**Comment by CoolerProYT** [comment]
> I think the issue is that they were trying to use the controller to input items while they needed to use the item input block below.

No, Is because when I use the book to build, and the controller at the transparent template not facing outside, instead if facing at 3 other side. When building it, the controller face outside wont show complete.

**Comment by TheBedrockMaster** [comment]
It's called input for a reason
