### ISSUE TITLE
Fission / Fusion Reactor does not work with Productive Bee recipes (ATM 9)

### ISSUE THREAD

**Issue by Szealand** [al132mc/alchemistry#338]
Hey, I am currently playing ATM 9 and tried to create a "Bee Periodic Table" since most, if not all, elements available in Chemlib / Alchemistry got a respective Bee. 
While all all recipes in the dissolver and combiner work perfectly fine the Fission and Fusion Reactor wont accept bee spawn eggs as a viable input (even though it is shown in the JEI). 
When you for example try to put a radioactive bee spawn egg into the fission reactor manually nothing will happen. If you force it to go into the reactor via the JEI overlay it turns the radioactive bee spawn egg into a no nbt data bee spawn egg and nothing else happens.
If this is an issue on your side I would love to see it fixed some time in the future and make it possible to complete my journey!

**Comment by Timbroglio** [comment]
Neither reactor has recipes for bees by default - if those are present in ATM9, they were added as part of the modpack. I'd recommend contacting the ATM9 developers to resolve this issue.
