### ISSUE TITLE
[Crash] Nuclearcraft

### ISSUE THREAD

**Issue by ScienceDrummer** [al132mc/alchemistry#39]
I get a crash with Nuclearcraft on startup.

Crash: https://paste.dimdev.org/gayixidumi.mccrash

**Comment by al132mc** [comment]
I have to wonder if there's a 3rd mod interfering somehow, I have the same version of nuclearcraft and alchemistry in my pack, but it starts up fine. In any case, I already uploaded v1.0.5 which /should/ fix this regardless of the cause. Please comment on this issue or open a new issue if you are still having problems after updating

**Comment by ScienceDrummer** [comment]
Seems to have fixed it.
