### ISSUE TITLE
Crash custom.xml

### ISSUE THREAD

**Issue by roulito** [al132mc/alchemistry#4]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Alchemistry (alchemistry)
Caused by: org.xml.sax.SAXParseException; systemId: 
/config/alchemistry/custom.xml; lineNumber: 2; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.

https://i.gyazo.com/026b659d7de8dba5604efb0192e109d2.png
no modification
Crash alchemistry 0.7.3
Not Crash Alchemistry 0.7.2

**Comment by al132mc** [comment]
Shoot. I've barely used XML before and I didn't realize you couldn't have comments before the XML declaration. Anyway, i've just uploaded v0.7.4 which should fix this and also prevent invalid XML from crashing on startup
