### ISSUE TITLE
[suggestion] AE2 Molecular combiner

### ISSUE THREAD

**Issue by daan7008** [al132mc/alchemistry#40]
It behaves the same like an molucular assembler from Applied Energistics. Put an interface next to it which supplies the recipes. Maybe put it in a seperate mod though, to keep it more modular. It would be fun if it has some kind of penalty to it. More power drain or the machine is kinda hard to make. Also the Interface that connects the ae2 network and the combiner could be a "chemical interface" just like the fluid interface

**Comment by al132mc** [comment]
Implemented your other idea in 1.0.17 instead
