### ISSUE TITLE
Salty Dissolver

### ISSUE THREAD

**Issue by jelaw21** [al132mc/alchemistry#41]
The Dissolver/Combiner is adding recipes for each of the Salt Oredict. In my pack its registering three with 8 Sodium Chloride and 1 with 16 Sodium Chloride. 

Appears that its adding a recipe for each oredict entry it finds.

**Comment by al132mc** [comment]
A version or two ago I fixed it so there is no longer a 1:16 recipe,  and the multiple 8 recipes will just have to exist for now, because there are many possible oredict entries for salt, and if something like unidict isn't fully integrated, then they may not overlap
