### ISSUE TITLE
[Suggestion] Gamestage Support or the Combiner 

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/alchemistry#45]
Would be great if you could add gamestage support to the combiner as it's the only machine that "creates" items instead of chemicals. So staging these recipes would make it possible to obtain other items as the player progresses in a pack.

**Comment by Fireztonez** [comment]
I totally agree a GameStage support will be nice, unless Alchemistry can possibly break somes progression in Modpacks using Stages to gate somes items or recipes.

**Comment by al132mc** [comment]
I just added Game Stage support for the Combiner in v1.0.22. I may add more machines, but I figured the Combiner was the highest priority

**Comment by Fireztonez** [comment]
Really nice, @al132mc, thank's for that! This will give me even more possibility for my modpack!
