### ISSUE TITLE
Ingots replaces other ingots

### ISSUE THREAD

**Issue by BlueCreeper160** [al132mc/alchemistry#46]
The crafting of ingots of elements, were replaced by the ingots of Alchemistry. ¿Is there any way to put in the config something like replace ingots?

**Comment by al132mc** [comment]
Could you give me more information please? Is this a modpack that you are creating or one that is publicly available? In either case, could you give me the modlist?

**Comment by al132mc** [comment]
Please comment if you are still having issues. You are probably looking for something like [unidict](https://minecraft.curseforge.com/projects/unidict)
