### ISSUE TITLE
Family Friendly Setting

### ISSUE THREAD

**Issue by jelaw21** [al132mc/alchemistry#48]
If possible, a config option to remove the illicit drug compounds.

**Comment by al132mc** [comment]
Implemented in v1.0.16

When enabled:
Cocaine -> Generic Cola
Psilocybin ->[Psyllium](https://en.wikipedia.org/wiki/Psyllium)
Mescaline -> [Mesquite](https://en.wikipedia.org/wiki/Mesquite)
