### ISSUE TITLE
Infinite-Bones-Bug

### ISSUE THREAD

**Issue by Meiko03** [al132mc/alchemistry#51]
If you put 3 Bones into a Chemical Dissolver they will be turned into 6 Hydroxylapatite. You then put them into a Chemical Combiner, it will then craft a Bone Block. The bone block can be put in a Factorizer from Thermal Expansion on Split mode, which will then give you 8 Bones. So you start with 3 Bones and at the end you have 8, thats +5 Bones each cycle. This will lead to infinite Hydroxylapatite, Bonemeal etc. The Factorizer's Bone Block to Bone recipe has to be removed, it breaks the game.

![BoneAbuse](https://user-images.githubusercontent.com/51014560/58365128-16a14880-7ec0-11e9-9701-3db9ea968c3d.PNG)

**Comment by al132mc** [comment]
Should be fixed in 1.0.20 on my end
