### ISSUE TITLE
Use unicode to display subscript

### ISSUE THREAD

**Issue by Jomik** [al132mc/alchemistry#6]
May I suggest using unicode to display subscript in the formulas?

`System.out.println("CO\u2082);` would print "CO<sub>2</sub>".

http://www.fileformat.info/info/unicode/char/2082/index.htm

**Comment by al132mc** [comment]
Ah, thank you. I hadn't looked into what it would take to add subscripts. This should be available in the next release

**Comment by al132mc** [comment]
v0.7.8 is now available with this feature
