### ISSUE TITLE
The Fusion Multiblock can not fuse any elements

### ISSUE THREAD

**Issue by magcicada** [al132mc/alchemistry#60]
The Fusion Multiblock does not have any recipes to fuse elements.

**Comment by al132mc** [comment]
It does, but there are many thousands of possible combinations, so I chose not to register them all in JEI for the sake of performance/memory/etc

**Comment by magcicada** [comment]
[zh_cn.zip](https://github.com/al132mc/alchemistry/files/3270541/zh_cn.zip)
Thanks for your reply,Then,I hope that you can update the lang file of Simplified Chinese,because the current lang file of Simplified Chinese is outdated and it has lots of mistakes,I revised and updated it，hope to be adopted.

**Comment by al132mc** [comment]
Yes, I will include this in the next update. Thank you.
