### ISSUE TITLE
[1.12.2] Can't craft Quatz Block in Combiner

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/alchemistry#62]
![image](https://user-images.githubusercontent.com/24524662/59285940-1dc1a800-8c6f-11e9-92d6-97d97c9f5a82.png)

![image](https://user-images.githubusercontent.com/24524662/59285957-24501f80-8c6f-11e9-894f-077bf2140532.png)

normal quartz works fine

**Comment by al132mc** [comment]
Yeah, recipe clash there, same thing with glowstone. I'll have to get those sorted out

**Comment by al132mc** [comment]
Fixed in 1.0.24
