### ISSUE TITLE
gregtech community edition integration

### ISSUE THREAD

**Issue by kurokamibe** [al132mc/alchemistry#74]
hi i would like to add custom recipe of ores from gregtech but it dont seem to work

```<recipe type="dissolver">
    <input>oreGarnierite</input>
    <output type="relative" rolls="1">
        <group probability="1">
			<item quantity="32">nickel</item>
			<item quantity="10">nickel</item>
			<item quantity="32">oxygen</item>
        </group>
    </output>
</recipe>
```
i wonder where am i wrong, should i add a "gregtech:oreGarnierite" enstead or something of the kind?

**Comment by al132mc** [comment]
I've pretty much stopped supporting the XML integration months ago. It may still work, but i'm not going to maintain it or troubleshoot it. I would highly recommend that you look to use the crafttweaker support instead which you can find [here](https://github.com/al132mc/alchemistry/wiki/CraftTweaker-Support)

**Comment by kurokamibe** [comment]
ah ok thanks i will try it
(maybe that XML integration should be removed from the wiki)

**Comment by al132mc** [comment]
I removed it from the wiki. Let me know if you managed to get this recipe working with crafttweaker
