### ISSUE TITLE
Add proper JEI recipe "+" support for Chemical Combiner

### ISSUE THREAD

**Issue by al132mc** [al132mc/alchemistry#8]

**Comment by CTB33391** [comment]
I second this so much.

**Comment by al132mc** [comment]
I've basically done this in v0.8.2. Using the [+] button now will automatically set the recipe template, so you don't have to fiddle around with stack sizes to do it by hand. Once you've done that you can just shift+click stacks and they'll go to the proper spot or set up some automation
