### ISSUE TITLE
[Suggestion] Electrochemical cell reactions in the Reactant Dynamo

### ISSUE THREAD

**Issue by tupoiu** [al132mc/alchemistry#84]
Similar to the recipe with Hydrogen and Liquid Oxygen currently, molten metals (Copper, Zinc, Tin, Iron) and moles of oxidising agent like Potassium Permanganate (KMnO4), Potassium Dichromate (K2Cr2O7), could react in the Reactant dynamo. A slightly more realistic adaptation would be solutions of the oxidising agents with moles of metals.

I think it would make sense to have RF outputs proportional to the electrochemical voltages (I'd happily figure these out if you decide to implement this).

**Comment by ghost** [comment]
Closing, should be on antimatter issue tracker instead https://github.com/al132mc/antimatter-chemistry/issues/190
