### ISSUE TITLE
[Suggestion] Seperate mask for compound element

### ISSUE THREAD

**Issue by Senjosei** [al132mc/alchemistry#85]
Hi im currently doing some retexturing and modeling for this mod but then i realized the compound elements are using the same texture and the colors are multiplied in. Can we have a seperate mask texture that specifies which part should be colorized? thnx
![2019-08-29_23 04 25](https://user-images.githubusercontent.com/17807328/63956958-af43f780-cab1-11e9-9ebb-7cc128cddf91.png)
Heres some part of my progress *ignore weird shading due to shaders

**Comment by ghost** [comment]
I don't know enough about 'masks' to know how exactly I should format that, but everything in this image that is not black or transparent is recolored, so hopefully that's enough information for you.
![compound](https://user-images.githubusercontent.com/39097092/63957452-02845e80-ca4e-11e9-99cc-6db2811e128b.png)

**Comment by Senjosei** [comment]
this is an example: say this is my base texture

![image](https://user-images.githubusercontent.com/17807328/63966571-c12f9580-cac5-11e9-8a3a-96d5bb7905f6.png)
with the current system everything including the bottle and cap is going to be colored like this

![image](https://user-images.githubusercontent.com/17807328/63966584-c7257680-cac5-11e9-9316-b186d18a7fec.png)
if i can specify a mask like this

![image](https://user-images.githubusercontent.com/17807328/63966588-cab8fd80-cac5-11e9-9eb8-afae844841c8.png)
the colored area will only be the black pixels so the result will be like this

![image](https://user-images.githubusercontent.com/17807328/63966595-cdb3ee00-cac5-11e9-90c7-4a9d4855d768.png)

could also make it so in the mask: black = 100% colorize strength, white = 0% colorize strength, and anything in between is x% strength

**Comment by ghost** [comment]
Sorry if i'm being dismissive, but it seems like you are more knowledgeable about this and could easily do it on your own for your own usage based on what I mentioned in the last comment?

**Comment by ghost** [comment]
Okay.. I decided to take a minute to do it anyway. I removed the black and greyscaled the rest, that should be good, right?

![compound](https://user-images.githubusercontent.com/39097092/63968494-8138c600-ca65-11e9-956b-d0bb524551d0.png)

**Comment by Senjosei** [comment]
Err what i mean is that right now if resource pack makers want to customize the way compund looks, every pixel in the compound.png will be tinted except black/transparent. It would be nice if either,
1. Theres a mask like i described above or
2. Seperate the "bottle" and the "contents" into seperate pngs and only tint the "contents"
I would try make a PR but im not familiar with kotlin+mc modding

**Comment by StellaBiscuit** [comment]
The best solution is to make different texture for EACH compound, like for the element. Ingot sould be like this too

**Comment by ghost** [comment]
I could, though it makes the ability to add custom compounds with crafttweaker significantly more difficult. Ease of adding new compounds is more important to me to be totally blunt. Maybe I will change this in 1.14, but in 1.12 this likely won't change.

**Comment by StellaBiscuit** [comment]
I'm making a modpack so this + the other issue I made really interest me.
I DON'T force you to do it, but if someone create element with crafttweaker, he would, most of the time, create compound of these elements so in anycase he will need to create the texture of the elements. It would just add an other step by making the compound texture + it would allow to make custom texture for each compound which is great. 
If you want, I could make every compound texture in 1 day
As I say I don't force you to do it
(Also adding a new texture is not the wrost thing to do, since it's just a color change and you doesn't need to add letter like for the elements)

**Comment by StellaBiscuit** [comment]
Just like this I made a 1.14.4 version of the element texture: 
![element](https://user-images.githubusercontent.com/53101126/64661491-dafca100-d412-11e9-8ecf-60570b255cde.png)
In order: Solid, Liquid, Gaz and Synthetic
I created these texture since I'm making a special resourcepack for my modpack

**Comment by ghost** [comment]
I don't plan on making any more changes like this to 1.12, I am no longer supporting 1.14 or 1.15, but the 1.16 version now uses masks like this.
