### ISSUE TITLE
QUESTION: Neutral or Negative elements

### ISSUE THREAD

**Issue by StellaBiscuit** [al132mc/alchemistry#87]
With Crafttweaker, is it possible to create an element like neutronium that would be element 0? Is it possible to create a negative one?

**Comment by StellaBiscuit** [comment]
Could you add the possibility to make element with ? and not a number? Like the one from minecraft education edition (Here is what I'm talking about: https://minecraft.gamepedia.com/Element#List_of_elements_and_isotopes )

**Comment by ghost** [comment]
To answer your question, this is not possible, but I will leave it open as a suggestion

**Comment by StellaBiscuit** [comment]
Here is the texture of the neutronium (that could be added to the mod directly)
1.12.2
![element_neutronium 1 12 2](https://user-images.githubusercontent.com/53101126/64662083-2b74fe00-d415-11e9-9113-0841e1c2e8f7.png)
1.14.4 (My resourcepack, the other texture can be see in the other issue)
![element_neutronium](https://user-images.githubusercontent.com/53101126/64662088-2f088500-d415-11e9-8a09-bb81221f4b2b.png)

**Comment by ghost** [comment]
The real trouble is that I have to re-wire a significant part of the code because it heavily utilizes numerical IDs/atomic numbers. The texture is not a concern.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your feature request as described won't fit the intentions we have with the mod. This doesn't mean that there isn't a chance that your idea can become an addon at a later point in time.
