### ISSUE TITLE
Chemical Combiner world lag

### ISSUE THREAD

**Issue by Gambigobilla** [al132mc/alchemistry#9]
Just placing Chemical Combiner causes massive frame rate drop. When i break/dismantle Chemical Combiner frame rate goes back to normal instantly. I don't see any errors or warnings in console.

Minecraft 1.12.2
Forge 14.23.4.2705
alchemistry-0.7.11
alib-1.0.1
Forgelin-1.7.4

**Comment by al132mc** [comment]
This should be fixed now in v0.7.12 which was just approved on curseforge. If you are still having issues then please comment again
