### ISSUE TITLE
[Suggestion] Gem synthesis: additional gems and more "realistic" approach

### ISSUE THREAD

**Issue by RbDrache** [al132mc/alchemistry#90]
Since there are many other gems in the world of modded Minecraft, I think it might be a good idea to implement gem synthesis to Alchemistry.
Currently, synthesis works by just putting some ingredients and energy together, so I'll just list a few examples of recipes.
Ruby and Sapphire: Al₂O₃
Topaz: Al₂SiO₄(F, OH)₂
Aquamarine: Be₃Al₂(SiO₃)₆ (Beryl)
This link will help: [https://www.compoundchem.com/wp-content/uploads/2014/06/The-Chemistry-of-Gemstone-Colours-2016.pdf](url)

You may have noticed that aquamarine and emerald shares the same ingredient: Beryl. Then what makes their color differ from each other? This brings us to the second part of this suggestion: more "realistic" approach of the gem synthesis.

The two Beryl-based gems actually differs in their impurities: Emerald has Chromium replacing Aluminium, and Aquamarine has iron 2+/3+ ions replacing Aluminium. However, the concentration is quite low, so I came up with a few solutions here:
1. Do it Alchemistry way, i.e. swapping the ingredients' position magically creates the impurities which results in color/structure change.
2. Add such impurities to the recipe as well. We can further improve this method by adding an option to turn on "gem hardmode" or something like that.
3. Add a gem synthesis device to deal with such problem; works like current synthesis device, but has slots for impurities such as Chromium and Iron.

Also, we can grow some gems the AE2 way, i,e, throw some crystals in concentrated hot solutions and it will grow bigger (into a perfect shape due to the limitations). Some of the gems can even be grown this way IRL.

Sorry for the wall of text, but I really hope this mod gets popular and this is a part of my (attempted) contribution.

**Comment by ghost** [comment]
I think this is beyond the scope/complexity of something I want to implement in Alchemistry, but if you still feel passionate about this you could open a new issue on the [Techemistry repo](https://github.com/al132mc/techemistry) the mod i'm making that has more complicated, more balanced mechanics.
