### ISSUE TITLE
Shift-clicking items into the Dissolver can move items into its output slots from your inventory

### ISSUE THREAD

**Issue by Hecklechet** [al132mc/alchemistry#92]
When shift-clicking in the GUI, for example, sodium while there is _already_ sodium in the output, it will fill whatever output slots contain sodium instead of the input. If all the output slots containing sodium are full, it still won't put the item into the input slot. This problem occurs with any item.

**Comment by ghost** [comment]
I am aware of this bug, though unsure how to fix. MC container code is kind of a nightmare

**Comment by Hecklechet** [comment]
Thank you for acknowledging. This is a nice mod and it's good to see it's still being worked on.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
