### ISSUE TITLE
Problem Removing Certain Combiner Recipes Using CraftTweaker

### ISSUE THREAD

**Issue by xlea99** [al132mc/alchemistry#95]
Hello, first of all I LOVE this mod. I missed Minechem so much and its so awesome to play an even BETTER version of it now in 1.12.

I'm currently working on a modpack with Alchemistry in it, and I'm removing all the combiner recipes for ingots (you'll only be able to use the combiner to make metal dusts out of elements), and I've been able to remove everything without a problem except for vanilla iron ingots and gold ingots. I've removed a ton of other ingots, but for some reason those two won't go. Weirder still, the message that they are being removed still pops up in the CraftTweaker log:

[AVAILABLE][CLIENT][INFO] Removed Chemical Combiner recipe for [<minecraft:gold_ingot>]
[AVAILABLE][CLIENT][INFO] Removed Chemical Combiner recipe for [<minecraft:iron_ingot>]

But it has no effect. I'm not sure if this is an issue with Alchemistry or CraftTweaker, but I just thought I'd check to see.

Thanks a bunch for your time!

**Comment by xlea99** [comment]
After further testing, it happens in a couple other isolated cases too. It doesn't work with <minecraft:cactus>, <minecraft:grass>, or <minecraft:mycelium>, as well as <minecraft:sapling:0-5>, but everything else seems to remove fine.

**Comment by ghost** [comment]
Hmm... i'm not quite sure what the issue is but i'll try to look into it

**Comment by xlea99** [comment]
@al132mc Thank you very much!

**Comment by ghost** [comment]
I was unable to duplicate this issue with just Crafttweaker and Alchemistry

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
