### ISSUE TITLE
[1.12.2] Chemical Dissolver - Lag and chunk updates

### ISSUE THREAD

**Issue by lunar-mc** [al132mc/alchemistry#96]
First off, this mod is incredible and thank you for making it. ❤

Not sure if this is a bug but I've noticed the Chemical Dissolver seems to cause an unusual lag spike compared to the other machines. The Dissolver forces around ~4 chunk updates constantly (compared to 0-1 for the combiner, atomizer etc), and is especially noticible with several dissolvers present. Tested in single player survival and creative modes. 

MC Version: 1.12.2
Alchemistry version: 1.0.35

Let me know if you need any other information.

Thanks!

**Comment by ghost** [comment]
Fixed in 1.12.2-40, sorry that it took me so long to fix this.
