### ISSUE TITLE
1.14.4: Interaction with machines also uses consumable

### ISSUE THREAD

**Issue by Zerahn** [al132mc/alchemistry#97]
If you have food or a usable molecule in your hand when you interact with a machine to access the GUI, the eating sound plays as the GUI opens, and the item is consumed by the player a second or so later.

**Comment by DracoNocte** [comment]
This bug is still present in 1.15.2.

**Comment by ghost** [comment]
I'm no longer supporting 1.14 or 1.15, but this has been fixed in 1.16 https://github.com/al132mc/alchemistry/issues/145
