### ISSUE TITLE
[Suggestion] Combiner Cactus recipe

### ISSUE THREAD

**Issue by Zerahn** [al132mc/alchemistry#98]
Cellulose is easy and you can make mescaline with little effort, but the only way to get the actual cactus is to find one somewhere. It'd be nice if you're playing with a skyblock or just can't find a desert.

**Comment by ghost** [comment]
Which version are you playing? I haven't checked 1.14 yet, but at least on 1.12 there is already a cactus combiner recipe 
![image](https://user-images.githubusercontent.com/39097092/68087193-e4a1f400-fe18-11e9-8a08-b6a75f84c3fb.png)

**Comment by Zerahn** [comment]
1.14 lol. i have JEI or whatever and it returns no results for creating a cactus, only breaking it down via the dissolver.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
