### ISSUE TITLE
Alchemistry (1.12.2) literally having no items

### ISSUE THREAD

**Issue by IDespiseChairs** [al132mc/alchemistry#99]
Hi so I am using a custom made modpack (havent tweaked anything in the code just added like 300 something mods) in 1.12.2 and for some reason the only item i can see is the book. Am i doing anything wrong? Keep in mind this is 1.12.2 and not 1.14 where the items are in a seperate mod. Atleast i think. Here is an image
![anyone else getting this](https://user-images.githubusercontent.com/57299649/68075693-dec5f780-fdb3-11e9-9b30-6fcecdd3f984.png)

**Comment by ghost** [comment]
Very strange, i'd have to wonder if another mod is interfering somehow. Could you provide me with a log file?

**Comment by IDespiseChairs** [comment]
Kinda new to the whole modding community, how do I get the logs? also the game takes like 30 minutes to load so sorry if i answer like 2 hours later lol

**Comment by ghost** [comment]
In the directory for the modpack there will be a folder called ``logs`` and inside that will be a file called ``latest.log``

Also, the game taking 30 minutes to load has absolutely nothing to do with Alchemistry and entirely to do with having 300+ mods. Alchemistry doesn't contribute more than a few seconds to load time.

**Comment by IDespiseChairs** [comment]
Alright! Heres the logs! also i know its not alchemistry causing my modpack to take so long to load, just mentioned it as an excuse for late reply :p heres the logs

[latest.log](https://github.com/al132mc/alchemistry/files/3809402/latest.log)

**Comment by ghost** [comment]
Well... I still have no idea what's going on here and nobody else has ever reported this as far as I know. If you still care about this being fixed or if anyone else is having this issue you can comment/create a new issue, but until then I am going to close this issue.
